export const SetNativeTranslate = (language, phrase_object, service) => {

    let translation = [
        { service: 'russia', russian: 'Россия', english: 'Russia', spanish: 'Rusia', turkish: 'Rusya', type: 'country' },
        { service: 'belarus', russian: 'Беларусь', english: 'Belarus', spanish: 'Bielorrusia', turkish: 'Belarus', type: 'country' },
        { service: 'kazahstan', russian: 'Казахстан', english: 'Kazahstan', spanish: 'Kazajistán', turkish: 'Kazakistan', type: 'country' },
        { service: 'kyrgyzstan', russian: 'Кыргызстан', english: 'Kyrgyzstan', spanish: 'Kirguistán', turkish: 'Kırgızistan', type: 'country' },

        { service: 'canada', russian: 'Канада', english: 'Canada', spanish: 'Canadá', turkish: 'Kanada', type: 'country' },
        { service: 'usa', russian: 'США', english: 'United States', spanish: 'EE.UU', turkish: 'ABD', type: 'country' },
        { service: 'united_kingdom', russian: 'Великобритания', english: 'United Kingdom', spanish: 'Gran Bretaña', turkish: 'Büyük Britanya', type: 'country' },
        { service: 'australia', russian: 'Австралия', english: 'Australia', spanish: 'Australia', turkish: 'Avustralya', type: 'country' },
        { service: 'new_zeland', russian: 'Новая зеландия', english: 'New zeland', spanish: 'Nueva Zelanda', turkish: 'Yeni Zelanda', type: 'country' },

        { service: 'spain', russian: 'Испания', english: 'Spain', spanish: 'Nueva Zelanda', turkish: 'Yeni Zelanda', type: 'country' },
        { service: 'sweden', russian: 'Швеция', english: 'Sweden', spanish: 'Suecia', turkish: 'İsveç', type: 'country' },
        { service: 'finland', russian: 'Финляндия', english: 'Finland', spanish: 'Finlandia', turkish: 'Finlandiya', type: 'country' },
        { service: 'montenegin', russian: 'Черногория', english: 'Montenegro', spanish: 'Montenegro', turkish: 'Karadağ', type: 'country' },
        { service: 'greece', russian: 'Герция', english: 'Greece', spanish: 'Hertia', turkish: 'Fıtık', type: 'country' },

        { service: 'arc', russian: 'В архиве', english: 'Archived', spanish: 'Archivado', turkish: 'Arşivlendi', type: 'order_status' },
        { service: 'new', russian: 'Новый', english: 'New', spanish: 'Nuevo', turkish: 'Yeni', type: 'order_status' },
        { service: 'postponed', russian: 'Отложен', english: 'Postponed', spanish: 'Pospuesto', turkish: 'Ertelenen', type: 'order_status' },
        { service: 'canceled', russian: 'Отменен', english: 'Canceled', spanish: 'Cancelado', turkish: 'İptal edildi', type: 'order_status' },
        { service: 'completed', russian: 'Выполнен', english: 'Completed', spanish: 'Terminado', turkish: 'Tamamlanmış', type: 'order_status' },
        { service: 'inWork', russian: 'В работе', english: 'In work', spanish: 'En curso', turkish: 'Devam ediyor', type: 'order_status' },
        { service: 'disrupt', russian: 'Сорван', english: 'Disrupted', spanish: 'Arrancado', turkish: 'Bozuldu', type: 'order_status' },

        { service: 'retail', russian: 'Для розничной торговли', english: 'Retail', spanish: 'Para la venta al por menor', turkish: 'Perakende için', type: 'user_info' },
        { service: 'wholesale', russian: 'Для оптовой торговли', english: 'Whole sale', spanish: 'Comercio mayorista', turkish: 'Toptan ticaret', type: 'user_info' },
        { service: 'food_delivery', russian: 'Для доставки продуктов', english: 'Food delivery', spanish: '', turkish: 'Yemek teslimatı için', type: 'user_info' },
        { service: 'ready_food_delivery', russian: 'Для доставки готовых блюд', english: 'Ready food delivery', spanish: 'Para la entrega de comidas preparadas', turkish: 'Hazır yemeklerin teslimi için', type: 'user_info' },
        { service: 'electronics_repair', russian: 'Для ремонта электроники', english: 'Electrinics repair', spanish: 'Para reparación de electrónica', turkish: 'Elektronik tamiri için', type: 'user_info' },
        { service: 'for_myself', russian: 'Для себя', english: 'For myself', spanish: 'Para mí', turkish: 'Kendim için', type: 'user_info' },

        { service: 'person', russian: 'Физическое лицо', english: 'Private person', spanish: 'Persona privada', turkish: 'Özel kişi', type: 'user_info' },
        { service: 'entity', russian: 'Юридическое лицо', english: 'Entity', spanish: 'Entidad', turkish: 'işletme', type: 'user_info' },
        { service: 'sole_trader', russian: 'Индивидуальный предприниматель', english: 'Sole trader', spanish: 'Comerciante único', turkish: 'Tek tüccar', type: 'user_info' },

        { service: 'walk', russian: 'Пешком', english: 'Walk', spanish: 'A pie', turkish: 'Yürüyerek', type: 'transport' },
        { service: 'bike', russian: 'Велосипед', english: 'Bike', spanish: 'Bicicleta', turkish: 'Bisiklet', type: 'transport' },
        { service: 'electric_scooter', russian: 'Электросамокат', english: 'Electric scooter', spanish: 'Scooter electrica', turkish: 'Elektrikli scooter', type: 'transport' },
        { service: 'scooter', russian: 'Мопед', english: 'Moto scooter', spanish: 'Moto scooter', turkish: 'Motorlu scooter', type: 'transport' },
        { service: 'car', russian: 'Легковой автомобиль', english: 'Car', spanish: 'Coche de pasajeros', turkish: 'Yolcu aracı', type: 'transport' },
        { service: 'combi', russian: 'Автомобиль комби', english: 'Combi car', spanish: 'Coche combinado', turkish: 'Kombi araba', type: 'transport' },
        { service: 'minibus', russian: 'Микроавтобуc', english: 'Minibus', spanish: 'Microbús', turkish: 'Minibüs', type: 'transport' },
        { service: 'truck', russian: 'Грузовой автомобиль', english: 'Truck', spanish: 'Camión', turkish: 'Kamyon', type: 'transport' },

        { service: '1.5', russian: '1.5 тонны', english: ' 1.5 tons', spanish: '1.5 toneladas', turkish: '1.5 ton', type: 'transport' },
        { service: '3', russian: '3 тонны', english: '3 tons', spanish: '3 toneladas', turkish: '3 ton', type: 'transport' },
        { service: '5', russian: '5 тонн', english: '5 tons', spanish: '5 toneladas', turkish: '5 ton', type: 'transport' },
        { service: '10', russian: '10 тонн', english: '10 tons', spanish: '10 toneladas', turkish: '10 ton', type: 'transport' },
        { service: '15', russian: '15 тонн', english: '15 tons', spanish: '15 toneladas', turkish: '15 ton', type: 'transport' },
        { service: '20', russian: '20 тонн', english: '20 tons', spanish: '20 toneladas', turkish: '20 ton', type: 'transport' },
        { service: 'load_capacity', russian: 'Грузоподъемность', english: 'Load capacity', spanish: 'Capacidad de carga', turkish: 'Yükleme kapasitesi', type: 'transport' },

        { service: 'open_side', russian: 'Открытый борт', english: 'Open side', spanish: 'Lado abierto', turkish: 'Açık taraf', type: 'transport' },
        { service: 'awing', russian: 'Тент', english: 'Awing', spanish: 'Toldo', turkish: 'Tente', type: 'transport' },
        { service: 'hard_top', russian: 'Фургон', english: 'Hard top', spanish: 'Camioneta', turkish: 'Kamyonet', type: 'transport' },
        { service: 'side_type', russian: 'Тип кузова', english: 'Side type', spanish: 'Tipo de carrocería del vehículo', turkish: 'Araç gövde tipi', type: 'transport' },

        { service: 'thermo_bag', russian: 'Термосумка', english: 'Thermo bag', spanish: 'Bolsa térmica', turkish: 'Termal çanta', type: 'equipment' },
        { service: 'thermo_van', russian: 'Изотермический фургон', english: 'Thermo van', spanish: 'Furgoneta isotérmica', turkish: 'Izotermal gövde', type: 'equipment' },
        { service: 'refrigerator_minus', russian: 'Рефрежиратор -7', english: 'Refrigerator -7', spanish: 'Refrigerador -7', turkish: 'Buzdolabı -7', type: 'equipment' },
        { service: 'refrigerator_plus', russian: 'Рефрежиратор +7', english: 'Refrigerator +7', spanish: 'Refrigerador +7', turkish: 'Buzdolabı +7', type: 'equipment' },
        { service: 'hydraulic_platform', russian: 'Гидавлическая платформа', english: 'Hydraulic platform', spanish: 'Plataforma hidráulica', turkish: 'Hidrolik platform', type: 'equipment' },
        { service: 'glass_stand', russian: 'Стойка для стекол', english: 'Glass stand', spanish: 'Estante de transporte de vidrio', turkish: 'Сam taşıma rafı', type: 'equipment' },
        { service: 'side_loading', russian: 'Боковая загрузка', english: 'Side loading', spanish: 'Carga lateral', turkish: 'Yan yükleme', type: 'equipment' },

        { service: 'filter_id', russian: 'id', english: 'id', spanish: 'id', turkish: 'id', type: 'filter' },
        { service: 'adress', russian: 'Адрес', english: 'Adress', spanish: 'La dirección', turkish: 'Adres', type: 'filter' },
        { service: 'partner', russian: 'Партнер', english: 'Partner', spanish: 'Compañero', turkish: 'Ortak', type: 'filter' },
        { service: 'cost_from', russian: 'Стоимость от', english: 'Cost from', spanish: 'Precio desde', turkish: 'Dan başlayan fiyatlar', type: 'filter' },
        { service: 'cost_to', russian: 'стоимость до', english: 'cost to', spanish: 'precio máximo', turkish: 'maksimum fiyat', type: 'filter' },
        { service: 'date_from', russian: 'Дата от', english: 'Date from', spanish: 'Fecha desde', turkish: 'Tarih başlıyor', type: 'filter' },
        { service: 'date_to', russian: 'дата до', english: 'date to', spanish: 'fecha máxima', turkish: 'maksimum tarih', type: 'filter' },

        { service: 'default', russian: 'По умолчанию', english: 'Default', spanish: 'Predeterminado', turkish: 'Varsayılan', type: 'sorting' },
        { service: 'from_auctions', russian: 'Сначала аукционы', english: 'Auctions at first', spanish: 'Subastas primero', turkish: 'Önce müzayedeler', type: 'sorting' },
        { service: 'from_orders', russian: 'Сначала заказы', english: 'Orders at first', spanish: 'Pedidos primero', turkish: 'Önce siparişler', type: 'sorting' },
        { service: 'latest_status', russian: 'По последнему статусу', english: 'By latest status', spanish: 'Por estado más reciente', turkish: 'Son duruma göre', type: 'sorting' },
        { service: 'transport_type', russian: 'По типу транспорта', english: 'By type of transport', spanish: 'Por tipo de transporte', turkish: 'Ulaşım türüne göre', type: 'sorting' },
        { service: 'ascending_cost', russian: 'По возрастанию стоимости', english: 'Ascending cost', spanish: 'Сosto ascendente', turkish: 'Yükselen maliyet', type: 'sorting' },
        { service: 'descending_cost', russian: 'По убыванию стоимости', english: 'Descending cost', spanish: 'Costo descendente', turkish: 'Azalan değer', type: 'sorting' },
        { service: 'new_old', russian: 'От новых к старым', english: 'From new to old', spanish: 'Fecha descendente', turkish: 'Azalan tarih', type: 'sorting' },
        { service: 'old_new', russian: 'От старых к новым', english: 'From old to new', spanish: 'Fecha ascendente', turkish: 'Tarihe göre sırala artan', type: 'sorting' },
        { service: 'sorting', russian: 'Сортировка', english: 'Sorting', spanish: 'Clasificación', turkish: 'Sıralamak', type: 'sorting' },
        { service: 'by_partner_name', russian: 'По наименованию', english: 'By name', spanish: 'Por nombre', turkish: 'Isme göre sırala', type: 'sorting' },
        { service: 'rating_up', russian: 'По возрастанию рейтинга', english: 'Rating ascending', spanish: 'Calificación ascendente', turkish: 'Derecelendirme artan', type: 'sorting' },
        { service: 'rating_down', russian: 'По убыванию рейтинга', english: 'Rating descending', spanish: 'Calificación descendente', turkish: 'Azalan derecelendirme', type: 'sorting' },

        { service: 'select', russian: 'Выбрать', english: 'Select', spanish: 'Elije', turkish: 'Seç', type: 'button' },
        { service: 'deselect', russian: 'Отменить выбор', english: 'Deselect', spanish: 'Deseleccionar', turkish: 'Seçimi kaldır', type: 'button' },
        { service: 'to_favorites', russian: 'Добавить в избранное', english: 'Add to favorites', spanish: 'Agregar a los favoritos', turkish: 'Favorilere ekle', type: 'button' },
        { service: 'from_favorites', russian: 'Убрать из избранного', english: 'Remove from favorites', spanish: 'Quitar de favoritos', turkish: 'Favorilerden çıkar', type: 'button' },

        { service: 'order', russian: 'Заказ', english: 'Order', spanish: 'Pedido', turkish: 'Sipariş', type: 'order_type' },
        { service: 'auction', russian: 'Аукцион', english: 'Auction', spanish: 'Subasta', turkish: 'Müzayede', type: 'order_type' },
        { service: 'template', russian: 'Шаблон', english: 'Template', spanish: 'Plantilla', turkish: 'Örneklem', type: 'order_type' },

        { service: 'status', russian: 'Статус', english: 'Status', spanish: 'Estado', turkish: 'Durum', type: 'field_name' },
        { service: 'phone', russian: 'Телефон', english: 'Phone', spanish: 'Teléfono', turkish: 'Telefon', type: 'field_name' },
        { service: 'order_comment', russian: 'Комментарий к заказу', english: 'Order comment', spanish: 'Comentario al pedido', turkish: 'Sipariş için yorum', type: 'field_name' },
        { service: 'transport', russian: 'Транспорт', english: 'Transport', spanish: 'Transporte', turkish: 'Ulaşım', type: 'field_name' },
        { service: 'cost', russian: 'Стоимость', english: 'Cost', spanish: 'Precio', turkish: 'Fiyat', type: 'field_name' },
        { service: 'available', russian: 'Доступен', english: 'Available', spanish: 'Disponible', turkish: 'Mevcut', type: 'field_name' },
        { service: 'start', russian: 'Откуда', english: 'Start', spanish: 'Comienzo', turkish: 'Başlangıç', type: 'field_name' },
        { service: 'adress_field_name', russian: 'Адрес', english: 'Adress', spanish: '', turkish: 'Adres', type: 'field_name' },
        { service: 'finish', russian: 'Последняя точка', english: 'Finish', spanish: 'Punto final', turkish: 'Son nokta', type: 'field_name' },
        { service: 'time', russian: 'Время', english: 'Time', spanish: 'Tiempo', turkish: 'Zaman', type: 'field_name' },
        { service: 'order_type', russian: 'Тип заказа', english: 'Order type', spanish: 'Tipo de orden', turkish: 'Sipariş türü', type: 'field_name' },
        { service: 'id', russian: 'id', english: 'id', spanish: 'id', turkish: 'id', type: 'field_name' },
        { service: 'last_order_status', russian: 'Последний статус', english: 'Last status', spanish: 'Último estado', turkish: 'Son durum', type: 'field_name' },
        { service: 'transport_tag_field_name', russian: 'Название', english: 'Name', spanish: 'Nombre', turkish: 'İsim', type: 'content' },
        { service: 'transport_type_field_name', russian: 'Способ доставки', english: 'Transport type', spanish: 'Método de entrega', turkish: 'Teslimat yöntemi', type: 'field_name' },
        { service: 'partner_name', russian: 'Наименование', english: 'Name', spanish: 'Nombre', turkish: 'İsim', type: 'field_name' },
        { service: 'number_of_members', russian: 'Количество участников', english: 'Number of members', spanish: 'Número de participantes', turkish: 'Katılımcı sayısı', type: 'field_name' },
        { service: 'groups_field_name', russian: 'Группы', english: 'Groups', spanish: 'Grupos', turkish: 'Gruplar', type: 'field_name' },
        { service: 'rating_field_name', russian: 'Рейтинг', english: 'Rating', spanish: 'Clasificación', turkish: 'Derecelendirme', type: 'field_name' },
        { service: 'arrival_time_field_name', russian: 'Время подачи', english: 'Arrival time', spanish: 'Tiempo de llegada', turkish: 'Varış zamanı', type: 'field_name' },
        { service: 'points_in_the_order', russian: 'Всего точек в заказе', english: 'Total points in the order', spanish: 'Total de direcciones en orden', turkish: 'Sırayla toplam adresler', type: 'field_name' },

        { service: 'carrier', russian: 'Перевозчик', english: 'Carrier', spanish: 'Transportista', turkish: 'Taşıyıcı', type: 'role' },
        { service: 'customer', russian: 'Заказчик', english: 'Customer', spanish: 'Cliente', turkish: 'Müşteri', type: 'role' },
        { service: 'manager', russian: 'Менеджер', english: 'Manager', spanish: 'Manager', turkish: 'Müdür', type: 'role' },
        { service: 'admin', russian: 'Администратор', english: 'Administrator', spanish: 'Administrador', turkish: 'Yönetici', type: 'role' },

        { service: 'not_specified', russian: 'Не указана', english: 'Not specified', spanish: 'No especificado', turkish: 'Belirtilmedi', type: 'content' },
        { service: 'no_orders', russian: 'Нет заказов', english: 'No orders', spanish: 'Sin pedidos', turkish: 'Emir yok', type: 'content' },
        { service: 'no_templates', russian: 'Нет шаблонов', english: 'No templates', spanish: 'Sin plantillas', turkish: 'Hiçbir şablonar', type: 'content' },
        { service: 'password', russian: 'Пароль', english: 'Password', spanish: 'Contraseña', turkish: 'Parola', type: 'content' },
        { service: 'email', russian: 'email', english: 'email', spanish: 'email', turkish: 'e-posta', type: 'content' },
        { service: 'selected_orders', russian: 'Выбрано заказов', english: 'Selected orders', spanish: 'Pedidos seleccionados', turkish: 'Seçili siparişler', type: 'content' },
        { service: 'to_all', russian: 'Всем', english: 'To all', spanish: 'Todo el mundo', turkish: 'Herkes', type: 'content' },
        { service: 'to_group', russian: 'Группе', english: 'To group', spanish: 'Para agrupar', turkish: 'Gruplamak için', type: 'content' },
        { service: 'to_partner', russian: 'Партнеру', english: 'To partner', spanish: 'A socio', turkish: 'Ortak olmak için', type: 'content' },
        { service: 'to_you', russian: 'Только вам', english: 'Just for you', spanish: 'Solo para ti', turkish: 'Sadece senin için', type: 'content' },
        { service: 'your_grop', russian: 'Вашей группе', english: 'To your group', spanish: 'A su grupo', turkish: 'Senin grubuna', type: 'content' },
        { service: 'auth_email', russian: 'Электронная почта для авторизации', english: 'Authorization email', spanish: 'Correo electrónico para autorización', turkish: 'Yetkilendirme için e-posta', type: 'content' },
        { service: 'your_rating', russian: 'Ваш рейтинг', english: 'Your rating', spanish: 'Tu clasificación', turkish: 'Derecelendirmeniz', type: 'content' },
        { service: 'name_surname_fathersname_content', russian: 'Фамилию, имя, отчество', english: 'First and last name', spanish: 'Nombre y apellido', turkish: 'Ad ve soyad', type: 'content' },
        { service: 'country_content', russian: 'Cтрана', english: 'Сountry', spanish: 'País', turkish: 'ülke', type: 'content' },
        { service: 'city_content', russian: 'Город', english: 'Сity', spanish: 'Ciudad', turkish: 'şehir', type: 'content' },
        { service: 'notification_email_content', russian: 'Email для уведомлений', english: 'Notification email', spanish: 'Email para notificaciones', turkish: 'Bildirimler için e-posta', type: 'content' },
        { service: 'adress_content', russian: 'Адрес', english: 'Postal adress', spanish: 'La dirección', turkish: 'Adres', type: 'content' },
        { service: 'phone_content', russian: 'Телефон', english: 'Phone', spanish: 'Teléfono', turkish: 'Telefon', type: 'content' },
        { service: 'delivery_for', russian: 'Для чего вам доставка', english: 'Why do you need delivery', spanish: 'Por qué necesita la entrega', turkish: 'Neden teslimata ihtiyacınız var', type: 'content' },
        { service: 'can_add', russian: 'Партнер может добваить вас с помощью кода', english: 'A partner can add you with a code', spanish: 'Un socio puede agregarte con un código', turkish: 'Bir iş ortağı sizi bir kodla ekleyebilir', type: 'content' },
        { service: 'subscription_status', russian: 'Состояние подписки', english: 'Subscription status', spanish: 'Estado de suscripción', turkish: 'Abonelik durumu', type: 'content' },
        { service: 'company_name_content', russian: 'Название компании', english: 'Company name', spanish: 'Nombre de empresa', turkish: 'Şirket ismi', type: 'content' },
        { service: 'website_content', russian: 'Сайт компании', english: 'Website', spanish: 'Sitio web', turkish: 'Web sitesi', type: 'content' },
        { service: 'company_inn_content', russian: 'ИНН', english: 'Tax number', spanish: 'Número de impuesto', turkish: 'Vergi numarası', type: 'content' },
        { service: 'legal_content', russian: 'Вы', english: 'You are', spanish: 'Eres un', turkish: 'Sen bir', type: 'content' },
        { service: 'passport_number_content', russian: 'Номер паспорта', english: 'Passport number', spanish: 'Número de pasaporte', turkish: 'Pasaport numarası', type: 'content' },
        { service: 'passport_issued_by_content', russian: 'Учреждение выдавшее паспорт', english: 'Passport issuing agency', spanish: 'Agencia emisora de pasaportes', turkish: 'Pasaport veren kurum', type: 'content' },
        { service: 'passport_date_of_issue_content', russian: 'Дата выдачи паспорта', english: 'Passport date of issue', spanish: 'Pasaporte fecha de emisión', turkish: 'Pasaport veriliş tarihi', type: 'content' },
        { service: 'account_status', russian: 'Статус аккаунта', english: 'Accaunt status', spanish: 'Estado de cuenta', turkish: 'Hesap durumu', type: 'content' },
        { service: 'completed_orders', russian: 'Завершено заказов', english: 'Completed orders', spanish: 'Órdenes completadas', turkish: 'Tamamlanan siparişler', type: 'content' },
        { service: 'disrupted_orders', russian: 'Сорвано заказов', english: 'Disrupted orders', spanish: 'Pedidos interrumpidos', turkish: 'Kesintiye uğramış siparişler', type: 'content' },
        { service: 'solvency', russian: 'Платежеспособность', english: 'Solvency', spanish: 'Solvencia', turkish: 'ödeme gücü', type: 'content' },
        { service: 'politeness', russian: 'Вежливость', english: 'Politeness', spanish: 'Cortesía', turkish: 'Naziklik', type: 'content' },
        { service: 'number_of_ratings', russian: 'Оценок', english: 'Ratings', spanish: 'Calificaciones', turkish: 'Oylar', type: 'content' },
        { service: 'total_rating', russian: 'Итоговый рейтинг', english: 'Total rating', spanish: 'Calificación total', turkish: 'toplam derecelendirme', type: 'content' },
        { service: 'loading_unloading', russian: 'Организация погрузки и выгрузки', english: 'Organization of loading and unloading', spanish: 'Organización de carga y descarga', turkish: 'Yükleme ve boşaltma organizasyonu', type: 'content' },
        { service: 'transport_quality', russian: 'Качество транспорта', english: 'Transport quality', spanish: 'Calidad del transporte', turkish: 'Taşıma kalitesi', type: 'content' },
        { service: 'no_downtime', russian: 'Отсутствие простоя по вине заказчика', english: 'No downtime due to the fault of the customer', spanish: 'Sin tiempo de inactividad por culpa del cliente', turkish: 'Müşterinin hatası nedeniyle kesinti yok', type: 'content' },
        { service: 'submission_fulfillment', russian: 'Своевременная подача и выполнение', english: 'Timely arrival and fulfillment', spanish: 'Llegada oportuna y cumplimiento', turkish: 'Zamanında varış ve yerine getirme', type: 'content' },
        { service: 'change_solvency', russian: 'Можно изменить оценку платежеспособности', english: 'You can change the assessment of solvency', spanish: 'Puedes cambiar la valoración de la solvencia', turkish: 'Ödeme gücü değerlendirmesini değiştirebilirsiniz', type: 'content' },
        { service: 'rate_solvency', russian: 'Можно оценить платежеспособность', english: 'You can rate solvency', spanish: 'Puedes calificar la solvencia', turkish: 'Ödeme gücünü derecelendirebilirsiniz', type: 'content' },
        { service: 'no_transport', russian: 'Нет траспорта, добавьте, чтобы получать заказы', english: 'No transport, add to receive orders', spanish: 'Sin transporte, añadir para recibir pedidos', turkish: 'Ulaşım yok, sipariş almak için ekleyin', type: 'content' },
        { service: 'drag_drop_transport', russian: 'Перетащите сюда или выберите фотографии транспорта и экипировки', english: 'Drag and drop here or select photos of transport and equipment', spanish: 'Arrastre y suelte aquí o seleccione fotos de transporte y equipo', turkish: 'Buraya sürükleyip bırakın veya ulaşım ve ekipman fotoğraflarını seçin', type: 'content' },
        { service: 'drag_drop_order', russian: 'Перетащите сюда или выберите фотографии груза или ориентиры на местности', english: 'Drag and drop here or select cargo photos or landmarks', spanish: 'Arrastre y suelte aquí o seleccione fotos de carga o puntos de referencia', turkish: 'Buraya sürükleyip bırakın veya kargo fotoğraflarını veya önemli noktaları seçin', type: 'content' },
        { service: 'drop_to_upload', russian: 'Отпустите файлы для загрузки', english: 'Drop files to upload', spanish: 'Soltar archivos para cargar', turkish: 'Yüklenecek dosyaları bırakın', type: 'content' },
        { service: 'partner_normal', russian: 'Нормальный', english: 'Normal', spanish: 'Normal', turkish: 'Normal', type: 'content' },
        { service: 'partner_blocked', russian: 'Заблокирован', english: 'Blocked', spanish: 'Obstruido', turkish: 'Bloke', type: 'content' },
        { service: 'partner_favorite', russian: 'В избранном', english: 'Favorite', spanish: 'Favorito', turkish: 'Favori', type: 'content' },
        { service: 'total_in_favorites', russian: 'В избранном', english: 'In favorites', spanish: 'En favoritos', turkish: 'Favorilerde', type: 'content' },
        { service: 'no_groups', russian: 'Нет групп', english: 'No groups', spanish: 'Sin grupos', turkish: 'Grup yok', type: 'content' },
        { service: 'legal_partner_info', russian: 'Организационно правовая форма', english: 'Organization legal form', spanish: 'Forma jurídica de la organización', turkish: 'Organizasyon yasal formu', type: 'content' },
        { service: 'type_of_customer_content', russian: 'Вид деятельности', english: 'Kind of activity', spanish: 'Tipo de actividad', turkish: 'Etkinlik türü', type: 'content' },
        { service: 'can_choose_groups', russian: 'Можно выбрать', english: 'You can choose', spanish: 'Tu puedes elegir', turkish: 'Seçebilirsiniz', type: 'content' },
        { service: 'no_ratings', russian: 'Нет оценок', english: 'No ratings', spanish: 'Sin calificaciones', turkish: 'Derecelendirme yok', type: 'content' },
        { service: 'no_partners', russian: 'Нет партнеров, они добавятся автоматически из заказов в работе, или добавьте их по id', english: 'There are no partners, they will be added automatically from orders in progress, or you can add them by id', spanish: 'No hay socios, se agregarán automáticamente desde los pedidos en curso, o puede agregarlos por id', turkish: 'Ortak yok, devam eden siparişlerden otomatik olarak eklenecekler veya bunları kimliğe göre ekleyebilirsiniz', type: 'content' },
        { service: 'main_slogan', russian: 'Здесь встречаются заказчики и перевозчики', english: 'Meeting place for customers and carriers', spanish: 'Lugar de encuentro de clientes y transportistas', turkish: 'Müşteriler ve taşıyıcılar için buluşma yeri', type: 'content' },
        { service: 'duration', russian: 'Продолжительность', english: 'Duration', spanish: 'Duración', turkish: 'Süre', type: 'content' },
        { service: 'distance', russian: 'Расстояние', english: 'Distance', spanish: 'Distancia', turkish: 'Mesafe', type: 'content' },
        { service: 'active_until', russian: 'Активна до', english: 'Active until', spanish: 'Válido hasta', turkish: 'Şu tarihe kadar geçerli', type: 'content' },
        { service: 'up_to', russian: 'До', english: 'Up to', spanish: 'Hasta', turkish: 'Kadar', type: 'content' },
        { service: 'mile', russian: 'mi', english: 'mi', spanish: 'milla', turkish: 'mil', type: 'content' },
        { service: 'kilometer', russian: 'km', english: 'km', spanish: 'km', turkish: 'km', type: 'content' },
        { service: 'all_country', russian: 'вся', english: 'all', spanish: 'todas', turkish: 'tüm', type: 'content' },
        { service: 'total_offers', russian: 'Сделано предложений', english: 'Total offers', spanish: 'Ofertas totales', turkish: 'Toplam teklifler', type: 'content' },
        { service: 'city_adress', russian: 'Город и адрес', english: 'City and adress', spanish: 'Ciudad y dirección', turkish: 'Şehir ve adres', type: 'content' },
        { service: 'no_time_limit', russian: 'Без срока', english: 'No time limits', spanish: 'Sin límites de tiempo', turkish: 'Zaman sınırı yok', type: 'content' },

        { service: 'sign_in', russian: 'Войти', english: 'Sign in', spanish: 'Iniciar sesión', turkish: 'Oturum aç', type: 'button' },
        { service: 'sign_out', russian: 'Выйти', english: 'Sign out', spanish: 'Salir', turkish: 'Сıkış yap', type: 'button' },
        { service: 'sign_up', russian: 'Зарегистрироваться', english: 'Sing up', spanish: 'Regístrate', turkish: 'Kaydolmak', type: 'button' },
        { service: 'send', russian: 'Отправить', english: 'Send', spanish: 'Enviar', turkish: 'Gönder', type: 'button' },
        { service: 'edit', russian: 'Редактировать', english: 'Edit', spanish: 'Editar', turkish: 'Düzenle', type: 'button' },
        { service: 'finish_button', russian: 'Завершить', english: 'Finish', spanish: 'Completar', turkish: 'Tamamla', type: 'button' },
        { service: 'cancel', russian: 'Отменить', english: 'Cancel', spanish: 'Cancelar', turkish: 'İptal etmek', type: 'button' },
        { service: 'take', russian: 'Взять в работу', english: 'Take it', spanish: 'Empezar', turkish: 'Başlamak', type: 'button' },
        { service: 'save', russian: 'Сохранить', english: 'Save', spanish: 'Salvar', turkish: 'Kurtarmak', type: 'button' },
        { service: 'create_template', russian: 'Создать шаблон', english: 'Create template', spanish: 'Crear plantilla', turkish: 'Şablon oluştur', type: 'button' },
        { service: 'postpone', russian: 'Отложить', english: 'Postpone', spanish: 'Posponer', turkish: 'Ertelemek', type: 'button' },
        { service: 'to_arc', russian: 'В архив', english: 'Move to archive', spanish: 'Mover al archivo', turkish: 'Arşive taşı', type: 'button' },
        { service: 'repeat', russian: 'Повторить', english: 'Repeat', spanish: 'Repetir', turkish: 'Tekrarlamak', type: 'button' },
        { service: 'copy', russian: 'Копировать', english: 'Copy', spanish: 'Copiar', turkish: 'Kopyala', type: 'button' },
        { service: 'complete', russian: 'Завершить', english: 'Finish', spanish: 'Completar', turkish: 'Tamamla', type: 'button' },
        { service: 'restore', russian: 'Восстановить', english: 'Restore', spanish: 'Restablecer', turkish: 'Yeniden kurmak', type: 'button' },
        { service: 'not_loading_button', russian: 'Не загрузка', english: 'Not loading', spanish: 'Sin cargar', turkish: 'Yüklenmiyor', type: 'button' },
        { service: 'not_arrival_button', russian: 'Не подача', english: 'Not arrival', spanish: 'No llegada', turkish: 'Varış değil', type: 'button' },
        { service: 'create', russian: 'Создать', english: 'Create', spanish: 'Crear', turkish: 'Yaratmak', type: 'button' },
        { service: 'delete', russian: 'Удалить', english: 'Delete', spanish: 'Eliminar', turkish: 'Silmek', type: 'button' },
        { service: 'delete_point', russian: 'Удалить точку', english: 'Delete point', spanish: 'Eliminar punto', turkish: 'Noktayı sil', type: 'button' },
        { service: 'close', russian: 'Закрыть', english: 'Close', spanish: 'Cerca', turkish: 'Kapat', type: 'button' },
        { service: 'all_cities', russian: 'Все города', english: 'All cities', spanish: 'Todas ciudades', turkish: 'Tüm şehirler', type: 'button' },
        { service: 'intercity_only', russian: 'Только межгород', english: 'Intercity only', spanish: 'Solo interurbano', turkish: 'Sadece şehirlerarası', type: 'button' },
        { service: 'send_code', russian: 'Отправить код', english: 'Send code', spanish: 'Enviar código', turkish: 'Kodu gönder', type: 'button' },
        { service: 'send_new_code', russian: 'Отправить новый код', english: 'Send new code', spanish: 'Envía un código nuevo', turkish: 'Yeni kodu gönder', type: 'button' },
        { service: 'save_and_sign_in', russian: 'Сохранить и войти', english: 'Save and sign in', spanish: 'Guardar e iniciar sesión', turkish: 'Kaydet ve giriş yap', type: 'button' },
        { service: 'orders', russian: 'Заказы', english: 'Orders', spanish: 'Pedidos', turkish: 'Emirler', type: 'button' },
        { service: 'create_order', russian: 'Создать заказ', english: 'Create order', spanish: 'Crear pedido', turkish: 'Sipariş oluştur', type: 'button' },
        { service: 'carriers', russian: 'Перевозчики', english: 'Carriers', spanish: 'Transportistas', turkish: 'Taşıyıcılar', type: 'button' },
        { service: 'customers', russian: 'Заказчики', english: 'Customers', spanish: 'Clientes', turkish: 'Müşteriler', type: 'button' },
        { service: 'account', russian: 'Аккаунт', english: 'Account', spanish: 'Cuenta', turkish: 'Hesap', type: 'button' },
        { service: 'order_editing', russian: 'Редактирование заказа', english: 'Order editing', spanish: 'Edición de pedidos', turkish: 'Sipariş düzenleme', type: 'button' },
        { service: 'settings', russian: 'Настройки', english: 'Settings', spanish: 'Ajustes', turkish: 'Ayarlar', type: 'button' },
        { service: 'transports', russian: 'Транспорт', english: 'Transports', spanish: 'Transporte', turkish: 'Ulaşım', type: 'button' },
        { service: 'arc_bookmark', russian: 'Архив', english: 'Archived', spanish: 'Archivo', turkish: 'Arşiv', type: 'button' },
        { service: 'new_bookmark', russian: 'Новые', english: 'New', spanish: 'Nuevo', turkish: 'Yeni', type: 'button' },
        { service: 'postponed_bookmark', russian: 'Отложенные', english: 'Postponed', spanish: 'Diferido', turkish: 'Ertelendi', type: 'button' },
        { service: 'canceled_bookmark', russian: 'Отмененые', english: 'Canceled', spanish: 'Cancelado', turkish: 'İptal edildi', type: 'button' },
        { service: 'completed_bookmark', russian: 'Выполненные', english: 'Completed', spanish: 'Completados', turkish: 'Tamamlanan', type: 'button' },
        { service: 'inWork_bookmark', russian: 'В работе', english: 'In work', spanish: 'En curso', turkish: 'Devam ediyor', type: 'button' },
        { service: 'templates_bookmark', russian: 'Шаблоны', english: 'Templates', spanish: 'Plantillas', turkish: 'Şablonlar', type: 'button' },
        { service: 'select_all', russian: 'Выбрать все', english: 'Select all', spanish: 'Seleccionar todos', turkish: 'Hepsini seç', type: 'button' },
        { service: 'reset', russian: 'Сбросить', english: 'Reset', spanish: 'Reajustar', turkish: 'Sıfırla', type: 'button' },
        { service: 'just_favorites', russian: 'Только избранное', english: 'Just favorites', spanish: 'Sólo favoritos', turkish: 'Sadece favoriler', type: 'button' },
        { service: 'clear_favorites', russian: 'Очистить избранное', english: 'Clear favorites', spanish: 'Claro favoritos', turkish: 'Sık kullanılanları temizle', type: 'button' },
        { service: 'reset_favorites', russian: 'Все', english: 'All', spanish: 'Todas', turkish: 'Tüm', type: 'button' },
        { service: 'send_activation_link', russian: 'Отправить ссылку', english: 'Send new link', spanish: 'Enviar nuevo enlace', turkish: 'Yeni bağlantı gönder', type: 'button' },
        { service: 'rate', russian: 'Оценить', english: 'Rate', spanish: 'Estimar', turkish: 'Oran', type: 'button' },
        { service: 'rate_customer', russian: 'Оцените заказчика', english: 'Rate the customer', spanish: 'Calificar al cliente', turkish: 'Müşteriyi değerlendirin', type: 'button' },
        { service: 'rate_carrier', russian: 'Оцените перевозчика', english: 'Rate the carrier', spanish: 'Valora al transportista', turkish: 'Taşıyıcıyı değerlendirin', type: 'button' },
        { service: 'add', russian: 'Добавить', english: 'Add', spanish: 'Agregar', turkish: 'Eklemek', type: 'button' },
        { service: 'add_point', russian: 'добавить точку', english: 'add point', spanish: 'Agregar punto', turkish: 'Nokta ekle', type: 'button' },
        { service: 'partners_list', russian: 'Список', english: 'List', spanish: 'Lista', turkish: 'Liste', type: 'button' },
        { service: 'groups', russian: 'Группы', english: 'Groups', spanish: 'Grupos', turkish: 'Gruplar', type: 'button' },
        { service: 'add_partner_by_id', russian: 'Добавить партнера по id', english: 'Add partner by id', spanish: 'Agregar socio por id', turkish: 'Kimliğe göre ortak ekle', type: 'button' },
        { service: 'partner_to_normal', russian: 'Убрать из избранного', english: 'Remove from favorites', spanish: 'Quitar de favoritos', turkish: 'Favorilerden çıkar', type: 'button' },
        { service: 'change_offer', russian: 'Изменить предложение', english: 'Change offer', spanish: 'Cambiar oferta', turkish: 'Teklifi değiştir', type: 'button' },
        { service: 'delete_offer', russian: 'Удалить предложение', english: 'Delete offer', spanish: 'Eliminar oferta', turkish: 'Teklifi sil', type: 'button' },
        { service: 'make_offer', russian: 'Сделать предложение', english: 'Make offer', spanish: 'Hacer oferta', turkish: 'Teklif yap', type: 'button' },
        { service: 'show_more', russian: 'Показать еще', english: 'Show more', spanish: 'Mostrar más', turkish: 'Daha fazla göster', type: 'button' },
        { service: 'show_all', russian: 'Показать все', english: 'Show all', spanish: 'Mostrar todos', turkish: 'Hepsini göster', type: 'button' },
        { service: 'roll_up_list', russian: 'Свернуть', english: 'Roll up the list', spanish: 'Enrolla la lista', turkish: 'Listeyi daralt', type: 'button' },
        { service: 'partner_to_blocked', russian: 'Заблокировать', english: 'Block', spanish: 'Bloquear', turkish: 'Blok', type: 'button' },
        { service: 'partner_from_blocked', russian: 'Разблокировать', english: 'Unblock', spanish: 'Desbloqueo', turkish: 'Kilidini aç', type: 'button' },
        { service: 'partner_to_favorite', russian: 'В избранное', english: 'To favorites', spanish: 'A favoritos', turkish: 'Favorilere', type: 'button' },
        { service: 'clear', russian: 'Очистить', english: 'Clear', spanish: 'Claro', turkish: 'Temizlemek', type: 'button' },
        { service: 'subscribe', russian: 'Оформить', english: 'Subscribe', spanish: 'Suscribir', turkish: 'Abone ol', type: 'button' },
        { service: 'renew', russian: 'Продлить', english: 'Renew', spanish: 'Prolongar', turkish: 'Aboneliğini', type: 'button' },
        { service: 'switch', russian: 'Перейти', english: 'Switch', spanish: 'Cambiar', turkish: 'Değiştirmek', type: 'button' },
        { service: 'intercity_only', russian: 'Только межгород', english: 'Intercity only', spanish: 'Solo interurbano', turkish: 'Sadece şehirlerarası', type: 'button' },
        { service: 'all_cities', russian: 'Все города', english: 'All cities', spanish: 'Todas las ciudades', turkish: 'Tüm şehirler', type: 'button' },
        { service: 'calculate_route', russian: 'Рассчитать  маршрут', english: 'Calculate route', spanish: 'Calcular ruta', turkish: 'Rotayı hesapla', type: 'button' },
        { service: 'clear_route', russian: 'Очистить маршрут', english: 'Clear route', spanish: 'Borrar ruta', turkish: 'Rotayı temizle', type: 'button' },
        { service: 'go_to_order', russian: 'Перейти к заказу', english: 'Go to order', spanish: 'Ir a pedido', turkish: 'Siparişe git', type: 'button' },
        { service: 'go_to_auction', russian: 'Перейти к аукциону', english: 'Go to auction', spanish: 'Ir a subasta', turkish: 'Açık artırmaya git', type: 'button' },
        { service: 'accept', russian: 'Подтвердить', english: 'Accept', spanish: 'Aceptar', turkish: 'Onayla', type: 'button' },
        { service: 'decline', russian: 'Отклонить', english: 'Decline', spanish: 'Rechazar', turkish: 'Reddet', type: 'button' },
        { service: 'tap_to_hide', russian: 'Каснитесь, чтобы скрыть', english: 'Tap to hide', spanish: 'Toca para ocultar', turkish: 'Gizlemek için dokunun', type: 'button' },

        { service: 'carriers_office', russian: 'Кабинет перевозчика', english: 'Сarrier`s office', spanish: 'Oficina del transportista', turkish: 'Taşıyıcının ofisi', type: 'header' },
        { service: 'customers_office', russian: 'Кабинет заказчика', english: 'Customer`s office', spanish: 'Oficina del cliente', turkish: 'Müşterinin ofisi', type: 'header' },
        { service: 'managers_office', russian: 'Кабинет менеджера', english: 'Managers office', spanish: 'Oficina del gerente', turkish: 'Yöneticinin ofisi', type: 'header' },
        { service: 'administrators_office', russian: 'Кабинет администратора', english: 'Administrator`s office', spanish: 'Oficina del administrador', turkish: 'Yönetici ofisi', type: 'header' },
        { service: 'registration', russian: 'Регистрация', english: 'Registration', spanish: 'Registro', turkish: 'Kayıt ol', type: 'header' },
        { service: 'authorization', russian: 'Авторизация', english: 'Authorization', spanish: 'Autorización', turkish: 'Yetkilendirme', type: 'header' },
        { service: 'password_recovery', russian: 'Восстановление пароля', english: 'Password recovery', spanish: 'Recuperación de contraseña', turkish: 'Şifre kurtarma', type: 'header' },
        { service: 'have_an_account', russian: 'Есть аккаунт? ', english: 'Have an account? ', spanish: '¿Hesabınız var mı?', turkish: 'Hesabınız var mı?', type: 'header' },
        { service: 'fill_account', russian: 'Заполните аккаунт и начнем', english: 'Fill in your account details and let`s get started.', spanish: 'Complete los detalles de su cuenta y comencemos', turkish: 'Hesap bilgilerinizi girin ve başlayalım', type: 'header' },
        { service: 'choose_subscription_plan', russian: 'Выберите подходящий тарифный план', english: 'Choose the right plan', spanish: 'Elige el plan adecuado', turkish: 'Doğru planı seçin', type: 'header' },

        { service: 'activated', russian: 'Аккаунт активирован', english: 'Account activated', spanish: 'Cuenta activada', turkish: 'Hesap etkinleştirildi', type: 'account_status' },
        { service: 'not_activated', russian: 'Аккаунт не активирован', english: 'Account not activated', spanish: 'Cuenta no activada', turkish: 'Hesap aktive edilmedi', type: 'account_status' },

        { service: 'not_empty', russian: 'не может быть пустым', english: 'can`t be empty', spanish: 'no puede estar vacío', turkish: 'boş olamaz', type: 'validation' },
        { service: 'to_short', russian: 'не может быть короче', english: 'can`t be shorter than', spanish: 'no puede ser más corto que', turkish: 'daha kısa olamaz', type: 'validation' },
        { service: 'to_long', russian: 'не может быть длиннее', english: 'can`t be longer than', spanish: 'no puede ser más largo que', turkish: 'şundan daha uzun olamaz', type: 'validation' },
        { service: 'format_error', russian: 'неверного формата', english: 'has wrong format', spanish: 'tiene un formato incorrecto', turkish: 'yanlış biçime sahip', type: 'validation' },
        { service: 'symbols', russian: 'символов', english: 'symbols', spanish: 'caracteres', turkish: 'karakterler', type: 'validation' },
        { service: 'compare_passwords', russian: 'пароли не совпадают', english: 'passwords do not match', spanish: 'las contraseñas no concuerdan', turkish: 'şifreler uyuşmuyor', type: 'validation' },
        { service: 'select_role', russian: 'выберите роль', english: 'select role', spanish: 'seleccionar rol', turkish: 'rol seç', type: 'validation' },
        { service: 'confirmation_code', russian: 'код подтверждения', english: 'confirmation code', spanish: 'código de confirmación', turkish: 'onay kodu', type: 'validation' },
        { service: 'select_side_type', russian: 'выберите тип кузова', english: 'select side type', spanish: 'seleccionar tipo de lado', turkish: 'yan tip seç', type: 'validation' },
        { service: 'select_load_capacity', russian: 'выберите грузоподъемность', english: 'select load capacity', spanish: 'seleccione la capacidad de carga', turkish: 'yük kapasitesi seç', type: 'validation' },
        { service: 'select_transport_type', russian: 'выберите тип транспорта', english: 'select transport type', spanish: 'seleccione el tipo de transporte', turkish: 'taşıma türünü seçin', type: 'validation' },
        { service: 'invalid_file_format', russian: 'недопустимый формат файла', english: 'invalid file format', spanish: 'formato de archivo inválido', turkish: 'geçersiz dosya formatı', type: 'validation' },
        { service: 'invalid_files_format', russian: 'недопустимый формат файлов', english: 'invalid files format', spanish: 'formato de archivos inválido', turkish: 'geçersiz dosya biçimi', type: 'validation' },
        { service: 'already_there', russian: 'уже есть', english: 'already there', spanish: 'ya ahi', turkish: 'zaten orada', type: 'validation' },
        { service: 'maximum', russian: 'Максимум', english: 'Maximum', spanish: 'Máximo', turkish: 'Maksimum', type: 'validation' },
        { service: 'images', russian: 'изображений', english: 'images', spanish: 'imágenes', turkish: 'resimler', type: 'validation' },
        { service: 'select_country', russian: 'Выберите страну', english: 'Select country', spanish: '', turkish: 'ülke seç', type: 'validation' },
        { service: 'select_city', russian: 'Выберите город из списка', english: 'Select a city from the list', spanish: 'Selecciona el país', turkish: '', type: 'validation' },
        { service: 'choose_legal_form', russian: 'выберите правовую форму', english: 'choose legal form', spanish: 'elegir forma jurídica', turkish: 'yasal formu seçin', type: 'validation' },
        { service: 'delivery_for_validation', russian: 'выберите для чего вам доставка', english: 'select why do you need delivery', spanish: 'seleccione por qué necesita la entrega', turkish: '', type: 'validation' },
        { service: 'select_adress', russian: 'Выберите адрес из списка', english: 'Select an adress from the list', spanish: '', turkish: 'neden teslimata ihtiyacınız olduğunu seçin', type: 'validation' },
        { service: 'comment', russian: 'Комментарий', english: 'Comment', spanish: '', turkish: '', type: 'validation' },
        { service: 'select_order_type', russian: 'выберите тип заказа', english: 'select order type', spanish: '', turkish: '', type: 'validation' },
        { service: 'cost_required', russian: 'введите стоимость, или выберите тип заказа аукцион', english: 'enter price value, or select auction order type', spanish: 'escriba el valor del precio o seleccione el tipo de orden de subasta', turkish: 'fiyat değerini yazın veya açık artırma siparişi türünü seçin', type: 'validation' },
        { service: 'select_group_validation', russian: 'выберите группу', english: 'select group', spanish: 'selecciona grupo', turkish: 'grup seç', type: 'validation' },
        { service: 'select_partner_validation', russian: 'выберите партнера', english: 'select partner', spanish: 'seleccionar socio', turkish: 'ortak seç', type: 'validation' },
        { service: 'comment_cant_be_empty', russian: 'комментарий не может быть пустым', english: 'comment can`t be empty', spanish: 'comentario no puede estar vacío', turkish: 'yorum boş olamaz', type: 'validation' },
        { service: 'comment_cannot_be_shorter', russian: 'комментарий не может быть короче', english: 'comment can`t be shorter than', spanish: 'comentario no puede ser más corto que', turkish: 'yorum şundan daha kısa olamaz', type: 'validation' },
        { service: 'comment_cannot_be_longer', russian: 'комментарий не может быть длиннее', english: 'comment can`t be longer than', spanish: 'comentario no puede ser más largo que', turkish: 'yorum şundan daha uzun olamaz', type: 'validation' },
        { service: 'arrival_time', russian: 'время подачи не может быть пустым', english: 'arrival time cannot be empty', spanish: 'la hora de llegada no puede estar vacía', turkish: 'varış saati boş olamaz', type: 'validation' },
        { service: 'finish_time', russian: 'время выполнения не может быть пустым', english: 'finish time cannot be empty', spanish: 'el tiempo de finalización no puede estar vacío', turkish: 'bitiş zamanı boş olamaz', type: 'validation' },
        { service: 'id_36', russian: 'длина id должна быть 36 симовлов', english: 'id length must be 36 characters', spanish: 'la longitud de identificación debe ser de 36 caracteres', turkish: 'kimlik uzunluğu 36 karakter olmalıdır', type: 'validation' },
        { service: 'id_not_empty', russian: 'id не может быть пустым', english: 'id can`t be empty', spanish: 'la identificación no puede estar vacía', turkish: 'kimlik boş olamaz', type: 'validation' },
        { service: 'password_hint', russian: 'пароль должен содержать минимум 1 символ A-Z, минимум 1 символ a-z, минимум 1 символ 0-9, и любой спецсимовол', english: 'password must contain at least 1 character A-Z, at least 1 character a-z, at least 1 character 0-9, and any special character', spanish: 'la contraseña debe contener al menos 1 carácter A-Z, al menos 1 carácter a-z, al menos 1 carácter 0-9 y cualquier carácter especial', turkish: 'şifre en az 1 karakter A-Z, en az 1 karakter a-z, en az 1 karakter 0-9 ve herhangi bir özel karakter içermelidir', type: 'validation' },
        { service: 'auth_email_validation', russian: 'email для авторизации', english: 'authorization email', spanish: 'correo electrónico de autorización', turkish: 'yetkilendirme e-postası', type: 'notification' },
        { service: 'name_surname_fathersname_validation', russian: 'Фамилия, имя, отчество', english: 'First and last name', spanish: 'Nombre y apellido', turkish: 'Ad ve soyad', type: 'validation' },

        { service: 'your_email', russian: 'Ваш email', english: 'Your email', spanish: 'Tu correo electrónico', turkish: 'E-posta adresiniz', type: 'place_holder' },
        { service: 'your_password', russian: 'Ваш пароль', english: 'Your password', spanish: 'Tu contraseña', turkish: 'Şifreniz', type: 'place_holder' },
        { service: 'who_are_you', russian: 'Вы заказчик или перевозчик?', english: 'Are you a customer or carrier?', spanish: '¿Eres cliente o transportista?', turkish: 'Müşteri veya taşıyıcı mısınız?', type: 'place_holder' },
        { service: 'password_repeat', russian: 'Пароль еще раз', english: 'Repeat password again', spanish: 'Repita la contraseña de nuevo', turkish: 'Şifreyi tekrar tekrarla', type: 'place_holder' },
        { service: 'Сonfirmation_code', russian: 'Код подтверждения', english: 'Сonfirmation code', spanish: 'Código de confirmación', turkish: 'Onay kodu', type: 'place_holder' },
        { service: 'transport_tag', russian: 'Название или государственный регистрационный знак', english: 'Name or license plate', spanish: 'Nombre o matrícula', turkish: 'İsim veya araç plakası', type: 'place_holder' },
        { service: 'enter_city', russian: 'Введите город', english: 'Type your city name', spanish: 'Escribe el nombre de tu ciudad', turkish: 'Şehrinizin adını yazın', type: 'place_holder' },
        { service: 'phone_place_holder', russian: 'Телефон', english: 'Phone', spanish: 'Teléfono', turkish: 'Telefon', type: 'place_holder' },
        { service: 'legal_place_holder', russian: 'Физическое лицо или бизнес', english: 'Individual or business', spanish: 'Particular o empresa', turkish: 'Bireysel veya ticari', type: 'place_holder' },
        { service: 'delivery_for_place_holder', russian: 'Для чего вам доставка', english: 'Why do you need delivery', spanish: 'Por qué necesita la entrega', turkish: 'Neden teslimata ihtiyacınız var', type: 'place_holder' },
        { service: 'company_name_place_holder', russian: 'Название компании', english: 'Company name', spanish: 'Nombre de empresa', turkish: 'Şirket ismi', type: 'place_holder' },
        { service: 'website_place_holder', russian: 'Сайт компании', english: 'Website', spanish: 'Sitio web', turkish: 'Web sitesi', type: 'place_holder' },
        { service: 'company_inn_place_holder', russian: 'ИНН', english: 'Tax number', spanish: 'Número de impuesto', turkish: 'Vergi numarası', type: 'place_holder' },
        { service: 'passport_number_place_holder', russian: 'Номер паспорта', english: 'Passport number', spanish: 'Número de pasaporte', turkish: 'Pasaport numarası', type: 'place_holder' },
        { service: 'passport_issued_by_place_holder', russian: 'Учреждение выдавшее паспорт', english: 'Passport issuing agency', spanish: 'Agencia emisora ​​de pasaportes', turkish: 'Pasaport veren kurum', type: 'place_holder' },
        { service: 'passport_date_of_issue_place_holder', russian: 'Дата выдачи паспорта', english: 'Passport date of issue', spanish: 'Fecha de emisión del pasaporte', turkish: 'Pasaport veriliş tarihi', type: 'place_holder' },
        { service: 'name_surname_fathersname_place_holder', russian: 'Фамилия, имя, отчество', english: 'First and last name', spanish: 'Nombre y apellido', turkish: 'Ad ve soyad', type: 'place_holder' },
        { service: 'adress_place_holder', russian: 'Адрес', english: 'Adress', spanish: 'Dirección', turkish: 'Adres', type: 'place_holder' },
        { service: 'order_type_place_holder', russian: 'Тип заказа', english: 'Order type', spanish: 'Tipo de pedido', turkish: 'Sipariş türü', type: 'place_holder' },
        { service: 'order_comment_place_holder', russian: 'Комментарий к заказу', english: 'Order comment', spanish: 'Comentario de pedido', turkish: 'Sipariş yorumu', type: 'place_holder' },
        { service: 'order_for_all', russian: 'Заказ для всех', english: 'Order for all', spanish: 'Pedido para todos', turkish: 'Herkes için sipariş', type: 'place_holder' },
        { service: 'order_for_group', russian: 'Заказ для группы', english: 'Order for group', spanish: 'Pedido para grupo', turkish: 'Grup için sipariş', type: 'place_holder' },
        { service: 'order_for_partner', russian: 'Заказ для партнера', english: 'Order for partner', spanish: 'Pedido para pareja', turkish: 'Ortak için sipariş', type: 'place_holder' },
        { service: 'select_group', russian: 'Выберите группу', english: 'Select group', spanish: 'Selecciona grupo', turkish: 'Grup seç', type: 'place_holder' },
        { service: 'select_partner', russian: 'Выберите партнера', english: 'Select partner', spanish: 'Seleccionar socio', turkish: 'Ortak seç', type: 'place_holder' },
        { service: 'enter_plase', russian: 'Введите местоположение', english: 'Enter place', spanish: 'Ingrese lugar', turkish: 'Yer girin', type: 'place_holder' },
        { service: 'enter_id', russian: 'Введите полученный от партнера id', english: 'Enter the id received from the partner', spanish: 'Ingrese la identificación recibida del socio', turkish: 'Ortaktan alınan kimliği girin', type: 'place_holder' },
        { service: 'group_name', russian: 'Название группы', english: 'Group name', spanish: 'Nombre del grupo', turkish: 'Grup ismi', type: 'place_holder' },
        { service: 'enter_a_city_to_track', russian: 'Введите город для отслеживания', english: 'Enter a city to track', spanish: 'Ingrese una ciudad para rastrear', turkish: 'Takip edilecek bir şehir girin', type: 'place_holder' },

        { service: 'orders_within_24_hours', russian: 'заказов за 24 часа', english: 'orders within 24 hours', spanish: 'pedidos en 24 horas', turkish: '24 saat içinde siparişler', type: 'subscription_options' },
        { service: 'auction_offers_in_24_hours', russian: 'предложений по аукционам за 24 часа', english: 'auction offers in 24 hours', spanish: 'ofertas de subasta en 24 horas', turkish: '24 saat içinde açık artırma teklifleri', type: 'subscription_options' },
        { service: 'take_orders_within_24_hours', russian: 'заказов в работу за 24 часа', english: 'take orders within 24 hours', spanish: 'tomar pedidos dentro de las 24 horas', turkish: '24 saat içinde sipariş almak', type: 'subscription_options' },
        { service: 'orders_in_the_city', russian: 'Заказы в городе', english: 'Orders in the city', spanish: 'Pedidos en la ciudad', turkish: 'Şehirdeki siparişler', type: 'subscription_options' },
        { service: 'orders_in_the_country', russian: 'Заказы в стране', english: 'Orders in the country', spanish: 'Pedidos en el país', turkish: 'Ülkedeki siparişler', type: 'subscription_options' },
        { service: 'points_in_order', russian: 'точек в заказе', english: 'points in order', spanish: 'puntos en orden', turkish: 'sırayla puan', type: 'subscription_options' },
        { service: 'countdown_from', russian: 'Отсчет с первого заказа в текущие сутки', english: 'Countdown from the first order on the current day', spanish: 'Cuenta regresiva desde el primer pedido en el da actual', turkish: 'Geçerli gündeki ilk siparişten geri sayım', type: 'subscription_options' },
        { service: 'ability_to_place_orders', russian: 'Радиус размещения заказов от центра города:', english: 'Radius of placing orders from the city center:', spanish: 'Radio de realización de pedidos desde el centro de la ciudad:', turkish: 'Şehir merkezinden sipariş verme yarıçapı:', type: 'subscription_options' },
        { service: 'number_of_tracking_cities', russian: 'Лимит дополнительных городов отслеживания:', english: 'Limit of additional tracking cities:', spanish: 'Límite de ciudades de seguimiento adicionales', turkish: 'Ek izleme şehirlerinin sınırı', type: 'subscription_options' },
        { service: 'points_in_order_description', russian: 'Количество точек в одном заказе до', english: 'Number of points in one order up to', spanish: 'Número de puntos en un pedido hasta', turkish: 'Bir siparişteki puan sayısı', type: 'subscription_options' },
        { service: 'none', russian: 'Нет подписки', english: 'No subcription', spanish: 'Sin subscripción', turkish: 'Abonelik yok', type: 'subscription_plans' },
        { service: 'free', russian: 'Бесплатная', english: 'Free', spanish: 'Gratis', turkish: 'Özgür', type: 'subscription_plans' },
        { service: 'standart', russian: 'Стандарт', english: 'Standart', spanish: 'Estándar', turkish: 'Standart', type: 'subscription_plans' },
        { service: 'professional', russian: 'Профессионал', english: 'Professional', spanish: 'Profesional', turkish: 'Profesyonel', type: 'subscription_plans' },
        { service: '30_days', russian: '30 дней', english: '30 days', spanish: '30 dias', turkish: '30 gün', type: 'subscription_plans' },
        { service: 'month', russian: 'Месяц', english: 'Month', spanish: 'Mes', turkish: 'Aylık', type: 'subscription_plans' },
        { service: 'year', russian: 'Год', english: 'Year', spanish: 'Año', turkish: 'Yıl', type: 'subscription_plans' },

        // from here change to native!

        // { service: 'code_sent', russian: 'Код отправлен', english: 'Сode sent', spanish: '', turkish: '', type: 'notification' },
        // { service: 'password_changed', russian: 'Пароль изиенен, доступ восстановлен, вы авторизованы', english: 'Password changed, access restored, you are logged in', spanish: '', turkish: '', type: 'notification' },
        // { service: 'logged_in', russian: 'Вы авторизованы', english: 'You are logged in', spanish: '', turkish: '', type: 'notification' },
        // { service: 'registered', russian: 'Вы зарегистрированы, ссылка для активации аккаунта отрправлена на указанный email', english: 'You are registered, a link to activate your account has been sent to the specified email', spanish: '', turkish: '', type: 'notification' },
        { service: 'new_orders_received', russian: 'Поступили новые заказы:', english: 'New orders received:', spanish: '', turkish: '', type: 'notification' },
        { service: 'new_order_received', russian: 'Поступил новый заказ', english: 'New order received', spanish: '', turkish: '', type: 'notification' },
        { service: 'orders_taken', russian: 'Взяты в работу заказы:', english: 'Orders taken:', spanish: '', turkish: '', type: 'notification' },
        { service: 'order_taken', russian: 'Взят в работу заказ', english: 'Order taken', spanish: '', turkish: '', type: 'notification' },
        { service: 'offers_accepted', russian: 'Вы приняли предложения по аукционам:', english: 'You have accepted offers for auctions:', spanish: '', turkish: '', type: 'notification' },
        { service: 'offer_accepted', russian: 'Вы приняли предложение по аукциону', english: 'You have accepted offer for auction', spanish: '', turkish: '', type: 'notification' },
        { service: 'offers_accepted_carrier', russian: 'Приняты ваши предложения по аукционам:', english: 'Customers accepted your offers for auctions:', spanish: '', turkish: '', type: 'notification' },
        { service: 'offer_accepted_carrier', russian: 'Принято ваше предложение по аукциону', english: '', spanish: 'Customer accepted your offer for auction', type: 'notification' },
        { service: 'start_doing', russian: 'можете приступать к выполнению', english: '', spanish: 'you can start doing', type: 'notification' },
        { service: 'postponed_orders', russian: 'Отложены заказы:', english: 'Postponed orders:', spanish: '', turkish: '', type: 'notification' },
        { service: 'postponed_order', russian: 'Отложен заказ', english: 'Postponed order:', spanish: '', turkish: '', type: 'notification' },
        { service: 'restored_orders', russian: 'Вы восстановили заказы:', english: 'You have restored orders:', spanish: '', turkish: '', type: 'notification' },
        { service: 'restored_order', russian: 'Вы восстановили заказ', english: 'You have restored order', spanish: '', turkish: '', type: 'notification' },
        { service: 'check_restored', russian: 'он находится в отложенных, можете отправить его после проверки', english: 'it is in postponed, you can send it after verification', spanish: '', turkish: '', type: 'notification' },
        { service: 'orders_canceled', russian: 'Отменены заказы:', english: 'Canceled orders:', spanish: '', turkish: '', type: 'notification' },
        { service: 'order_canceled', russian: 'Отменен заказ', english: 'Canceled order:', spanish: '', turkish: '', type: 'notification' },
        { service: 'not_loading', russian: 'В связи с незагрузкой', english: 'Due to not loading', spanish: '', turkish: '', type: 'notification' },
        { service: 'non_arrival', russian: 'В связи с не подачей', english: 'Due to non-arrival', spanish: '', turkish: '', type: 'notification' },
        { service: 'affect_your_rating', russian: 'обратите внимание, это влияет на ваш рейтинг', english: 'please note that this will affect your rating', spanish: '', turkish: '', type: 'notification' },
        { service: 'affect_carrier_rating', russian: 'Это повлияет на рейтинг перевозчика', english: 'This will affect the rating of the carrier', spanish: '', turkish: '', type: 'notification' },
        { service: 'affect_customer_rating', russian: 'Это повлияет на рейтинг заказчика', english: 'This will affect the rating of the customer', spanish: '', turkish: '', type: 'notification' },
        { service: 'restore_to_resend', russian: 'восстановите его для повторной отправки', english: 'restore it to resend the order', spanish: '', turkish: '', type: 'notification' },
        { service: 'canceled_disrupted_orders', russian: 'Вы отменили сорванные заказы:', english: 'You canceled disrupted orders:', spanish: '', turkish: '', type: 'notification' },
        { service: 'canceled_disrupted_order', russian: 'Вы отменили сорванный заказ', english: 'You canceled disrupted order', spanish: '', turkish: '', type: 'notification' },
        { service: 'completed_orders', russian: 'Завершены заказы:', english: 'Completed orders:', spanish: '', turkish: '', type: 'notification' },
        { service: 'completed_order', russian: 'Завершен заказ', english: 'Completed order:', spanish: '', turkish: '', type: 'notification' },
        { service: 'customer_completed_orders', russian: 'Заказчик завершил заказы:', english: 'The customer completed orders:', spanish: '', turkish: '', type: 'notification' },
        { service: 'customer_completed_order', russian: 'Заказчик завершил заказ', english: 'The customer completed order:', spanish: '', turkish: '', type: 'notification' },
        { service: 'new_offers', russian: 'Поступили новые предложения к аукционам', english: 'New offers for auctions', spanish: '', turkish: '', type: 'notification' },
        { service: 'changed_offers', russian: 'Измемены предложения к аукционам', english: 'Changed offers for auctions', spanish: '', turkish: '', type: 'notification' },
        { service: 'removed_offers', russian: 'Удалены предложения к аукционам', english: 'Removed offers for auctions', spanish: '', turkish: '', type: 'notification' },
        { service: 'new_offer', russian: 'Поступило новое предложение к аукциону', english: 'New offer for auction', spanish: '', turkish: '', type: 'notification' },
        { service: 'changed_offer', russian: 'Измемено предложение к аукциону', english: 'Changed offer for auction', spanish: '', turkish: '', type: 'notification' },
        { service: 'removed_offer', russian: 'Удалено предложение к аукциону', english: 'Removed offer for auction', spanish: '', turkish: '', type: 'notification' },
        { service: 'order_notifications', russian: 'Заказ', english: 'Order', spanish: '', turkish: '', type: 'notification' },
        { service: 'orders_notifications', russian: 'Заказы:', english: 'Orders:', spanish: '', turkish: '', type: 'notification' },
        { service: 'auction_notifications', russian: 'Аукцион', english: 'Auction', spanish: '', turkish: '', type: 'notification' },
        { service: 'auctions_notifications', russian: 'Аукционы:', english: 'Auctions:', spanish: '', turkish: '', type: 'notification' },
        { service: 'converted_one', russian: 'преобразован', english: 'converted', spanish: '', turkish: '', type: 'notification' },
        { service: 'converted_many', russian: 'преобразованы', english: 'converted', spanish: '', turkish: '', type: 'notification' },
        { service: 'can_take_it', russian: 'вы можете взять в работу на текущих условиях', english: 'you can take it on current terms', spanish: '', turkish: '', type: 'notification' },
        { service: 'to_order', russian: 'в заказ', english: 'to order', spanish: '', turkish: '', type: 'notification' },
        { service: 'to_auction', russian: 'в аукцион', english: 'to auction', spanish: '', turkish: '', type: 'notification' },
        { service: 'canceled_point', russian: 'Отменена точка', english: 'Canceled point', spanish: '', turkish: '', type: 'notification' },
        { service: 'canceled_points', russian: 'Отменены точки:', english: 'Canceled points:', spanish: '', turkish: '', type: 'notification' },
        { service: 'completed_point', russian: 'Завершена точка', english: 'Completed point', spanish: '', turkish: '', type: 'notification' },
        { service: 'postponed_point', russian: 'Отложена точка', english: 'Postponed point', spanish: '', turkish: '', type: 'notification' },
        { service: 'postponed_points', russian: 'Отложены точки', english: 'Postponed points    ', spanish: '', turkish: '', type: 'notification' },
        { service: 'completed_points', russian: 'Завершены точки:', english: 'Completed points:', spanish: '', turkish: '', type: 'notification' },
        { service: 'restored_point', russian: 'Восстановлена точка', english: 'Restored point', spanish: '', turkish: '', type: 'notification' },
        { service: 'restored_points', russian: 'Восстановлены точки:', english: 'Restored points:', spanish: '', turkish: '', type: 'notification' },
        { service: 'in_work_point', russian: 'Взята в работу точка', english: 'Taken into work point', spanish: '', turkish: '', type: 'notification' },
        { service: 'in_work_points', russian: 'Взяты в работу точки', english: 'Taken into work points', spanish: '', turkish: '', type: 'notification' },
        { service: 'on_order', russian: 'по заказу', english: '', spanish: 'on order', type: 'notification' },
        { service: 'on_auction', russian: 'по аукциону', english: '', spanish: 'on auction', type: 'notification' },
        { service: 'on_orders', russian: 'по заказам', english: 'on orders:', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_converted', russian: 'Вы преобразовали', english: 'You converted', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_postponed', russian: 'Вы отложили', english: 'You have postponed', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_restored', russian: 'Вы восстановили', english: 'You have restored', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_canceled', russian: 'Вы отменили', english: 'You have canceled', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_send', russian: 'Вы отправили', english: 'You have send', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_took', russian: 'Вы взяли в работу', english: 'You have took', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_finished', russian: 'Вы завершили', english: 'You have finished', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_deleted', russian: 'Вы удалили', english: 'You have deleted', spanish: '', turkish: '', type: 'notification' },
        { service: 'to_arc_notification', russian: 'Перенесен в архив', english: 'Archived', spanish: '', turkish: '', type: 'button' },
        { service: 'you_moved_to_arc', russian: 'в ахиве', english: 'archived', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_opened', russian: 'Вы открыли', english: 'You have opened', spanish: '', turkish: '', type: 'notification' },
        { service: 'the', russian: ' ', english: 'The', spanish: '', turkish: '', type: 'notification' },
        { service: 'orders_notification', russian: 'Заказы', english: 'Orders', spanish: '', turkish: '', type: 'notification' },
        { service: 'for_editing', russian: 'для редактирования', english: 'for editing', spanish: '', turkish: '', type: 'notification' },
        { service: 'form_from_order', russian: 'форму из заказа', english: 'form from order', spanish: '', turkish: '', type: 'notification' },
        { service: 'form_from_auction', russian: 'форму из аукциона', english: 'form from auction', spanish: '', turkish: '', type: 'notification' },
        { service: 'form_from_template', russian: 'форму из шаблона', english: 'form from template', spanish: '', turkish: '', type: 'notification' },
        { service: 'check_restored_arc', russian: 'проверьте доступность для партнеров и время в заказе перед отправкой', english: 'check the availability for partners and the time in the order before sending', spanish: '', turkish: '', type: 'notification' },
        { service: 'name_surname_fathersname', russian: 'фамилию, имя, отчество', english: 'first and last name', spanish: '', turkish: '', type: 'notification' },
        { service: 'country', russian: 'страну', english: 'country', spanish: '', turkish: '', type: 'notification' },
        { service: 'city', russian: 'город и адрес', english: 'city', spanish: '', turkish: '', type: 'notification' },
        { service: 'company_inn', russian: 'ИНН', english: 'tax number', spanish: '', turkish: '', type: 'notification' },
        { service: 'company_name', russian: 'название компании', english: 'company name', spanish: '', turkish: '', type: 'notification' },
        { service: 'company_adress', russian: 'адрес', english: 'adress', spanish: '', turkish: '', type: 'notification' },
        { service: 'website', russian: 'сайт компании', english: 'website', spanish: '', turkish: '', type: 'notification' },
        { service: 'legal', russian: 'организационно правовую форму', english: 'organization legal form', spanish: '', turkish: '', type: 'notification' },
        { service: 'passport_issued_by', russian: 'учреждение выдавшее паспорт', english: 'passport issuing agency', spanish: '', turkish: '', type: 'notification' },
        { service: 'passport_date_of_issue', russian: 'дату выдачи паспорта', english: 'passport date of issue', spanish: '', turkish: '', type: 'notification' },
        { service: 'passport_number', russian: 'номер паспорта', english: 'passport number', spanish: '', turkish: '', type: 'notification' },
        { service: 'phone', russian: 'телефон', english: 'phone', spanish: '', turkish: '', type: 'notification' },
        { service: 'type_of_customer', russian: 'вид деятельности', english: 'kind of activity', spanish: '', turkish: '', type: 'notification' },
        { service: 'email', russian: 'email для уведомлений', english: 'notification email', spanish: '', turkish: '', type: 'notification' },
        { service: 'authEmail', russian: 'email для авторизации, на него отправлена ссылка для подтверждения аккаунта', english: 'email for authorization, a link was sent to it to verify the account', spanish: '', turkish: '', type: 'notification' },
        { service: 'rated_carrier', russian: 'Вы оценили перевозчика', english: 'You have rated carrier', spanish: '', turkish: '', type: 'notification' },
        { service: 'rated_customer', russian: 'Вы оценили заказчика', english: 'You have rated customer', spanish: '', turkish: '', type: 'notification' },
        { service: 'rated_customer_solvency', russian: 'Вы оценили платежеспособность заказчика', english: 'You have rated customer solvency', spanish: '', turkish: '', type: 'notification' },
        { service: 'rated_carrier_solvency', russian: 'Вы оценили платежеспособность перевозчика', english: 'You have rated carrier solvency', spanish: '', turkish: '', type: 'notification' },
        { service: 'order_editing_canceled', russian: 'Редактирование заказа отменено', english: 'Order editing canceled', spanish: '', turkish: '', type: 'notification' },
        { service: 'auction_editing_canceled', russian: 'Редактирование аукциона отменено', english: 'Auction editing canceled', spanish: '', turkish: '', type: 'notification' },
        { service: 'point_limit', russian: 'Лимит колличества точек в заказе с вашей подпиской', english: 'Point limit per order with your subscription is', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_can_change_subscription', russian: 'Вы можете изменть подписку в разделе аккаунт', english: 'You can change your subscription in the account section', spanish: '', turkish: '', type: 'notification' },
        { service: 'edited', russian: 'Отредактирован', english: 'Edited', spanish: '', turkish: '', type: 'notification' },
        { service: 'created_and_send', russian: 'создан и отправлен', english: 'created and send', spanish: '', turkish: '', type: 'notification' },
        { service: 'created_and_postponed', russian: 'создан и отложен', english: 'created and postponed', spanish: '', turkish: '', type: 'notification' },
        { service: 'created', russian: 'Создан', english: 'Created', spanish: '', turkish: '', type: 'notification' },
        { service: 'partner_added', russian: 'Вы добавили партнера', english: 'You have added a partner', spanish: '', turkish: '', type: 'notification' },
        { service: 'group_created', russian: 'Вы создали группу', english: 'Created group:', spanish: '', turkish: '', type: 'notification' },
        { service: 'group_deleted', russian: 'Вы удалили группу', english: 'Deleted group:', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_added', russian: 'Вы добавили', english: 'You have added', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_created', russian: 'Вы создали', english: 'You have created', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_blocked', russian: 'Вы заблокировали', english: 'You have blocked', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_have_changed_status', russian: 'Вы изменили статус', english: 'You have changed status of', spanish: '', turkish: '', type: 'notification' },
        { service: 'you_have_changed', russian: 'Вы изменили', english: 'You have changed', spanish: '', turkish: '', type: 'notification' },
        { service: 'customer_notification', russian: 'заказчика', english: 'customer', spanish: '', turkish: '', type: 'notification' },
        { service: 'carrier_notification', russian: 'перевозчика', english: 'carrier', spanish: '', turkish: '', type: 'notification' },
        { service: 'to_favorite_notification', russian: 'в избранное', english: 'to favorites', spanish: '', turkish: '', type: 'notification' },
        { service: 'to_normal_notification', russian: 'на наормальный', english: 'to normal', spanish: '', turkish: '', type: 'notification' },
        { service: 'reason_of_cancellation', russian: 'Укажите причину в комментарии', english: 'State your reason in a comment', spanish: '', turkish: '', type: 'notification' },
        { service: 'last', russian: 'последнюю', english: 'last', spanish: '', turkish: '', type: 'notification' },
        { service: 'point', russian: 'точку', english: 'point', spanish: '', turkish: '', type: 'notification' },
        { service: 'of_order', russian: 'заказа', english: 'of order', spanish: '', turkish: '', type: 'notification' },
        { service: 'subscription_cities_limit', russian: 'Вы достигли лимта городов для отслеживания заказов доступного с вашей подпиской. Вы можете проверить и изменить план в разделе аккаунт', english: 'You have reached the limit of cities for tracking orders available with your subscription. You can check and change the plan in the account section', spanish: '', turkish: '', type: 'notification' },
        { service: 'city_already_added', russian: 'Вы уже добавили город отслеживания заказов', english: 'You have already added an order tracking city:', spanish: '', turkish: '', type: 'notification' },
        { service: 'added_order_tracking_city', russian: 'Добавлен город отслеживания заказов', english: 'Added order tracking city', spanish: '', turkish: '', type: 'notification' },
        { service: 'no_need_to_add', russian: 'Нет необходимости добавлять', english: 'No need to add', spanish: '', turkish: '', type: 'notification' },
        { service: 'your_default_city', russian: ', это ваш город по умолчанию', english: ', this is your default city', spanish: '', turkish: '', type: 'notification' },
        { service: 'new_link_send', russian: 'Новая ссылка для активации аккаунта отправлена на', english: 'A new account activation link has been sent to', spanish: '', turkish: '', type: 'notification' },
        { service: 'response_will_not_be_read', russian: 'Это автоматическое уведомление, ответ не будет прочитан', english: 'This is an automatic notification, the response will not be read', spanish: '', turkish: '', type: 'notification' },
        { service: 'new_order_auction', russian: 'Появился новый', english: 'New', spanish: '', turkish: '', type: 'server_notification' },
        { service: 'suitable_for_your_transport', russian: 'подходящий для вашего транспорта', english: 'which is suitable for your transport', spanish: '', turkish: '', type: 'notification' },
        { service: 'suitable_for_your_transport_many', russian: 'подходящие для вашего транспорта', english: 'which is suitable for your transport', spanish: '', turkish: '', type: 'notification' },
        { service: 'new_orders_auctions', russian: 'Появились новые', english: 'New', spanish: '', turkish: '', type: 'server_notification' },
        { service: 'for_which_you_made_an_offer', russian: 'по которому вы делали предложение', english: 'for which you made an offer', spanish: '', turkish: '', type: 'notification' },
        { service: 'when_the_customer_sends_it', russian: ', когда заказчик его отправит', english: ', when the customer sends it', spanish: '', turkish: '', type: 'notification' },
        { service: 're_converted_to_an_auction', russian: 'снова преобразован в аукцион, ожидайте решения заказчика', english: 're-converted to an auction, please wait for the customer`s decision', spanish: '', turkish: '', type: 'notification' },
        { service: 'but_postponed', russian: 'но отложен', english: ', but it`s postponed', spanish: '', turkish: '', type: 'notification' },
        { service: 'total_offers', russian: 'всего предложений:', english: 'total offers:', spanish: '', turkish: '', type: 'notification' },
        { service: 'rejected_your_offer', russian: 'Отклонено ваше предложение к аукциону', english: 'Rejected your offer for auction', spanish: '', turkish: '', type: 'notification' },
        { service: 'customer_has_preferred', russian: 'заказчик отдал предпочтение другому перевозчику, рассмотрите другие заказы или аукционы', english: 'the customer has preferred another carrier, consider other orders or auctions', spanish: '', turkish: '', type: 'notification' },
        { service: 'by_carrier', russian: 'перевозчиком', english: 'by carrier', spanish: '', turkish: '', type: 'notification' },
        { service: 'by_customer', russian: 'заказчиком', english: 'by customer', spanish: '', turkish: '', type: 'notification' },
        { service: 'finished', russian: 'завершен', english: 'finished', spanish: '', turkish: '', type: 'notification' },
        // { service: 'you_can_restore', russian: 'вы можете восстановить заказ', english: 'you can restore the order', spanish: '', turkish: '', type: 'notification' },


        { service: 'sms_messaging', russian: 'Уведомлять по смс', english: 'Notify by sms', spanish: '', turkish: '', type: 'settings' },
        { service: 'email_messaging', russian: 'Уведомлять по email', english: 'Notify by email', spanish: '', turkish: '', type: 'settings' },
    ]

    let translatedText

    if (service) {
        translatedText = translation.find(el => el.service === service)[language]
    } else {
        translatedText = phrase_object[language]
        if (translatedText) {
            translatedText = translatedText.join(' ')
        }
    }

    return translatedText
}
