import { makeAutoObservable } from "mobx";

export default class TranslateStore {
    constructor() {
        this._language = 'english'

        this._translation = [
            { service: 'russia', russian: 'Россия', english: 'Russia', spain: '', color: '', type: 'country' },
            { service: 'greece', russian: 'Герция', english: 'Greece', spain: '', color: '', type: 'country' },
            { service: 'canada', russian: 'Канада', english: 'Canada', spain: '', color: '', type: 'country' },
            { service: 'spain', russian: 'Испания', english: 'Spain', spain: '', color: '', type: 'country' },
            { service: 'sweden', russian: 'Швеция', english: 'Sweden', spain: '', color: '', type: 'country' },
            { service: 'finland', russian: 'Финляндия', english: 'Finland', spain: '', color: '', type: 'country' },
            { service: 'montenegin', russian: 'Черногория', english: 'Montenegro', spain: '', color: '', type: 'country' },

            // { service: 'krasnodar', russian: 'Краснодар', english: 'Krasnodar', spain: '', color: '', type: 'city' },
            // { service: 'sevastopol', russian: 'Севастополь', english: '', spain: '', color: '', type: 'city' },
            // { service: 'simferopol', russian: 'Симферополь', english: '', spain: '', color: '', type: 'city' },
            // { service: 'novorossiysk', russian: 'Новороссийск', english: '', spain: '', color: '', type: 'city' },
            // { service: 'rostov_on_don', russian: 'Ростов на Дону', english: '', spain: '', color: '', type: 'city' },
            // { service: 'gelendzhik', russian: 'Геленджик', english: 'Gelendzhik', spain: '', color: '', type: 'city' },

            { service: 'arc', russian: 'В архиве', english: 'Archived', spain: '', color: 'rgb(210,219,236, 0.8)', type: 'order_status' },
            { service: 'new', russian: 'Новый', english: 'New', spain: '', color: 'rgb(129, 199, 132,0.8)', type: 'order_status' },
            { service: 'postponed', russian: 'Отложен', english: 'Postponed', spain: '', color: 'rgb(241,196,15,0.8)', type: 'order_status' },
            { service: 'canceled', russian: 'Отменен', english: 'Canceled', spain: '', color: 'rgb(254, 111, 103,0.8)', type: 'order_status' },
            { service: 'completed', russian: 'Выполнен', english: 'Completed', spain: '', color: 'rgb(214,232,255,0.8)', type: 'order_status' },
            { service: 'inWork', russian: 'В работе', english: 'In work', spain: '', color: 'rgb(254, 145, 40,0.8)', type: 'order_status' },
            { service: 'disrupt', russian: 'Сорван', english: 'Disrupted', spain: '', color: 'rgb(254, 111, 103,0.8)', type: 'order_status' },

            { service: 'order', russian: 'Заказ', english: 'Order', spain: '', color: '', type: 'order_type' },
            { service: 'auction', russian: 'Аукцион', english: 'Auction', spain: '', color: '', type: 'order_type' },

            { service: 'retail', russian: 'Розничной торговли', english: 'Retail', color: '', spain: '', type: 'user_info' },
            { service: 'wholesale', russian: 'Оптовой торговли', english: 'Whole sale', color: '', spain: '', type: 'user_info' },
            { service: 'food_delivery', russian: 'Доставки продуктов', english: 'Food delivery', spain: '', color: '', type: 'user_info' },
            { service: 'ready_food_delivery', russian: 'Доставки готовых блюд', english: 'Ready food delivery', spain: '', color: '', type: 'user_info' },
            { service: 'electronics_repair', russian: 'Ремонта электроники', english: 'Electrinics repair', spain: '', color: '', type: 'user_info' },
            { service: 'for_myself', russian: 'Себя', english: 'For myself', spain: '', color: '', type: 'user_info' },

            { service: 'person', russian: 'Физическое лицо', english: 'Private person', spain: '', color: '', type: 'user_info' },
            { service: 'entity', russian: 'Юридическое лицо', english: 'Entity', spain: '', color: '', type: 'user_info' },
            { service: 'sole_trader', russian: 'Индивидуальный предприниматель', english: 'Sole trader', spain: '', color: '', type: 'user_info' },

            { service: 'walk', russian: 'Пешком', english: 'Walk', spain: '', color: '', type: 'transport' },
            { service: 'bike', russian: 'Велосипед', english: 'Bike', spain: '', color: '', type: 'transport' },
            { service: 'electric_scooter', russian: 'Electric scooter', english: '', spain: '', color: '', type: 'transport' },
            { service: 'scooter', russian: 'Мопед', english: 'Moto scooter', spain: '', color: '', type: 'transport' },
            { service: 'car', russian: 'Легковой автомобиль', english: 'Car', spain: '', color: '', type: 'transport' },
            { service: 'combi', russian: 'Автомобиль комби', english: 'Combi car', spain: '', color: '', type: 'transport' },
            { service: 'minibus', russian: 'Микроавтобуc', english: 'Minibus', spain: '', color: '', type: 'transport' },
            { service: 'truck', russian: 'Грузовой автомобиль', english: 'Truck', spain: '', color: '', type: 'transport' },
            // обдумать единицы измерения
            { service: '1.5', russian: '1.5 тонны', english: '', spain: '', color: '', type: 'transport' },
            { service: '3', russian: '3 тонны', english: '', spain: '', color: '', type: 'transport' },
            { service: '5', russian: '5 тонн', english: '', spain: '', color: '', type: 'transport' },
            { service: '10', russian: '10 тонн', english: '', spain: '', color: '', type: 'transport' },
            { service: '15', russian: '15 тонн', english: '', spain: '', color: '', type: 'transport' },
            { service: '20', russian: '20 тонн', english: '', spain: '', color: '', type: 'transport' },

            { service: 'open_side', russian: 'Открытый борт', english: 'Open side', spain: '', color: '', type: 'transport' },
            { service: 'awing', russian: 'Тент', english: 'Awing', spain: '', color: '', type: 'transport' },
            { service: 'hard_top', russian: 'Фургон', english: 'Hard top', spain: '', color: '', type: 'transport' },

            { service: 'thermo_bag', russian: 'Термосумка', english: 'Thermo bag', spain: '', color: '', type: 'equipment' },
            { service: 'thermo_van', russian: 'Изотермический фургон', english: 'Thermo van', spain: '', color: '', type: 'equipment' },
            { service: 'refrigerator_minus', russian: 'Рефрежиратор -7', english: 'Refrigerator -7', spain: '', color: '', type: 'equipment' },
            { service: 'refrigerator_plus', russian: 'Рефрежиратор +7', english: 'Refrigerator +7', spain: '', color: '', type: 'equipment' },
            { service: 'hydraulic_platform', russian: 'Гидавлическая платформа', english: 'Hydraulic platform', spain: '', color: '', type: 'equipment' },
            { service: 'glass_stand', russian: 'Стойка для стекол', english: 'Glass stand', spain: '', color: '', type: 'equipment' },
            { service: 'side_loading', russian: 'Боковая загрузка', english: 'Side loading', spain: '', color: '', type: 'equipment' },
            { service: 'thermo_van', russian: 'Изотермический фургон', english: 'Thermo van', spain: '', color: '', type: 'equipment' },

            //пока не востребовано
            { service: 'normal', russian: '', english: '', spain: '', color: 'rgb(241,196,15,0.8)', type: 'partner' },
            { service: 'priority', russian: '', english: '', spain: '', color: 'rgb(129, 199, 132,0.8)', type: 'partner' },
            { service: 'blocked', russian: '', english: '', spain: '', color: 'rgb(254, 111, 103,0.8)', type: 'partner' },

            { service: 'name_surname_fathersname', russian: 'фамилию, имя, отчество', english: 'first and last name', spain: '', color: '', type: 'account' },
            { service: 'country', russian: 'страну', english: 'country', spain: '', color: '', type: 'account' },
            { service: 'city', russian: 'город и адрес', english: 'city', spain: '', color: '', type: 'account' },
            { service: 'company_inn', russian: 'ИНН', english: 'tax number', spain: '', color: '', type: 'account' },
            { service: 'company_name', russian: 'название компании', english: 'company name', spain: '', color: '', type: 'account' },
            { service: 'company_adress', russian: 'адрес', english: 'adress', spain: '', color: '', type: 'account' },
            { service: 'website', russian: 'сайт компании', english: 'website', spain: '', color: '', type: 'account' },
            { service: 'legal', russian: 'организационно правовую форму', english: 'organization legal form', spain: '', color: '', type: 'account' },
            { service: 'passport_issued_by', russian: 'учреждение выдавшее паспорт', english: 'passport issuing agency', spain: '', color: '', type: 'account' },
            { service: 'passport_date_of_issue', russian: 'дату выдачи паспорта', english: 'passport date of issue', spain: '', color: '', type: 'account' },
            { service: 'passport_number', russian: 'номер паспорта', english: 'passport number', spain: '', color: '', type: 'account' },
            { service: 'phone', russian: 'телефон', english: 'phone', spain: '', color: '', type: 'account' },
            { service: 'type_of_customer', russian: 'вид деятельности', english: 'kind of activity', spain: '', color: '', type: 'account' },
            { service: 'email_updated', russian: 'email для уведомлений', english: 'notification email', spain: '', color: '', type: 'account' },
            { service: 'authEmail_updated', russian: 'email для авторизации, на него отправлена ссылка для подтверждения аккаунта', english: 'email for authorization, a link was sent to it to verify the account', spain: '', color: '', type: 'account' },

            { service: 'none', russian: 'Нет подписки', english: 'No subscription', spain: '', color: 'grey', type: 'subscription' },
            { service: 'free', russian: 'Free', english: 'Free', spain: '', color: 'rgb(254, 111, 103,0.8)', type: 'subscription' },
            { service: 'standart', russian: 'Standart', english: 'Standart', spain: '', color: 'rgb(241,196,15,0.8)', type: 'subscription' },
            { service: 'standart_year', russian: 'Standart', english: 'Standart', spain: '', color: 'rgb(241,196,15,0.8)', type: 'subscription' },
            { service: 'professional', russian: 'Professional', english: 'Professional', spain: '', color: 'rgb(129, 199, 132,0.8)', type: 'subscription' },
            { service: 'professional_year', russian: 'Professional', english: 'Professional', spain: '', color: 'rgb(129, 199, 132,0.8)', type: 'subscription' },

            { service: 'activated', russian: 'Аккаунт активирован', english: 'Account activated', spain: '', color: 'rgb(129, 199, 132,0.8)', type: 'account_status' },
            { service: 'not_activated', russian: 'Аккаунт не активирован', english: 'Account not activated', spain: '', color: 'rgb(254, 111, 103,0.8)', type: 'account_status' },

            { service: 'sign_in', russian: 'Войти', english: 'Sign in', spain: '', color: '', type: 'button' },
            { service: 'sign_out', russian: 'Выйти', english: 'Sign out', spain: '', color: '', type: 'button' },
            { service: 'sign_up', russian: 'Зарегистрироваться', english: 'Sing up', spain: '', color: '', type: 'button' },
            { service: 'send', russian: 'Отправить', english: 'Send', spain: '', color: '', type: 'button' },
            { service: 'cancel', russian: 'Отменить', english: 'Cancel', spain: '', color: '', type: 'button' },
            { service: 'create_template', russian: 'Создать шаблон', english: 'Create template', spain: '', color: '', type: 'button' },
            { service: 'postpone', russian: 'Отложить', english: 'Postpone', spain: '', color: '', type: 'button' },
            { service: 'to_arc', russian: 'В архив', english: 'Move to archive', spain: '', color: '', type: 'button' },
            { service: 'repeat', russian: 'Повторить', english: 'Repeat', spain: '', color: '', type: 'button' },
            { service: 'copy', russian: 'Копировать', english: 'Copy', spain: '', color: '', type: 'button' },
            { service: 'complete', russian: 'Завершить', english: 'Finish', spain: '', color: '', type: 'button' },
            { service: 'restore', russian: 'Восстановить', english: 'Restore', spain: '', color: '', type: 'button' },
            { service: 'create', russian: 'Создать', english: 'Create', spain: '', color: '', type: 'button' },
            { service: 'delete', russian: 'Удалить', english: 'Delete', spain: '', color: '', type: 'button' },
            { service: 'сlose', russian: 'Закрыть', english: 'Close', spain: '', color: '', type: 'button' },
            { service: 'all_cities', russian: 'Все города', english: 'All cities', spain: '', color: '', type: 'button' },
            { service: 'intercity_only', russian: 'Только межгород', english: 'Intercity only', spain: '', color: '', type: 'button' },
            { service: 'send_code', russian: 'Отправить код', english: 'Send code', spain: '', color: '', type: 'button' },
            { service: 'send_new_code', russian: 'Отправить новый код', english: 'Send new code', spain: '', color: '', type: 'button' },
            { service: 'save_and_sign_in', russian: 'Сохранить и войти', english: 'Save and sign in', spain: '', color: '', type: 'button' },
            { service: 'orders', russian: 'Заказы', english: 'Orders', spain: '', color: '', type: 'button' },
            { service: 'create_order', russian: 'Создать заказ', english: 'Create order', spain: '', color: '', type: 'button' },
            { service: 'carriers', russian: 'Перевозчики', english: 'Carriers', spain: '', color: '', type: 'button' },
            { service: 'customers', russian: 'Заказчики', english: 'Customers', spain: '', color: '', type: 'button' },
            { service: 'account', russian: 'Аккаунт', english: 'Account', spain: '', color: '', type: 'button' },
            { service: 'order_editing', russian: 'Редактирование заказа', english: 'Order editing', spain: '', color: '', type: 'button' },
            { service: 'settings', russian: 'Настройки', english: 'Settings', spain: '', color: '', type: 'button' },
            { service: 'transports', russian: 'Транспорт', english: 'Transports', spain: '', color: '', type: 'button' },
            { service: 'arc_bookmark', russian: 'Архиве', english: 'Archived', spain: '', color: 'rgb(210,219,236, 0.8)', type: 'button' },
            { service: 'new_bookmark', russian: 'Новые', english: 'New', spain: '', color: 'rgb(129, 199, 132,0.8)', type: 'button' },
            { service: 'postponed_bookmark', russian: 'Отложенные', english: 'Postponed', spain: '', color: 'rgb(241,196,15,0.8)', type: 'button' },
            { service: 'canceled_bookmark', russian: 'Отмененые', english: 'Canceled', spain: '', color: 'rgb(254, 111, 103,0.8)', type: 'button' },
            { service: 'completed_bookmark', russian: 'Выполненые', english: 'Completed', spain: '', color: 'rgb(214,232,255,0.8)', type: 'button' },
            { service: 'inWork_bookmark', russian: 'В работе', english: 'In work', spain: '', color: 'rgb(254, 145, 40,0.8)', type: 'button' },
            { service: 'templates_bookmark', russian: 'Шаблоны', english: 'Templates', spain: '', color: 'rgb(254, 145, 40,0.8)', type: 'button' },
            { service: 'select_all', russian: 'Выбрать все', english: 'Select all', spain: '', color: '', type: 'button' },
            { service: 'reset', russian: 'Сбросить', english: 'Reset', spain: '', color: '', type: 'button' },
            { service: 'just_favorites', russian: 'Только избранное', english: 'Just favorites', spain: '', color: '', type: 'button' },
            { service: 'clear_favorites', russian: 'Очистить избранное', english: 'Clear favorites', spain: '', color: '', type: 'button' },
            { service: 'reset_favorites', russian: 'Все', english: 'All', spain: '', color: '', type: 'button' },

            // { service: '', russian: '', english: '', spain: '', color: '', type: 'button' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'button' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'button' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'button' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'button' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'button' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'button' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'button' },

            { service: 'default', russian: 'По умолчанию', english: 'Default', spain: '', color: '', type: 'sort' },
            { service: 'from_auctions', russian: 'Сначала аукционы', english: 'Auctions at first', spain: '', color: '', type: 'sort' },
            { service: 'from_orders', russian: 'Сначала заказы', english: 'Orders at first', spain: '', color: '', type: 'sort' },
            { service: 'latest_status', russian: 'По последнему статусу', english: 'By latest status', spain: '', color: '', type: 'sort' },
            { service: 'transport_type', russian: 'По типу транспорта', english: 'By type of transport', spain: '', color: '', type: 'sort' },
            { service: 'ascending_cost', russian: 'По возрастанию стоимости', english: 'Ascending cost', spain: '', color: '', type: 'sort' },
            { service: 'descending_cost', russian: 'По убыванию стоимости', english: 'Descending cost', spain: '', color: '', type: 'sort' },
            { service: 'new_old', russian: 'От новых к старым', english: 'From new to old', spain: '', color: '', type: 'sort' },
            { service: 'old_new', russian: 'От старых к новым', english: 'From old to new', spain: '', color: '', type: 'sort' },

            // { service: '', russian: '', english: '', spain: '', color: '', type: 'sort' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'sort' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'sort' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'sort' },

            // { service: '', russian: '', english: '', spain: '', color: '', type: 'filter' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'filter' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'filter' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'filter' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'filter' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'filter' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'filter' },        

            { service: 'carriers_office', russian: 'Кабинет перевозчика', english: 'Сarrier`s office', spain: '', color: '', type: 'header' },
            { service: 'customers_office', russian: 'Кабинет заказчика', english: 'Customer`s office', spain: '', color: '', type: 'header' },
            { service: 'managers_office', russian: 'Кабинет менеджера', english: 'Managers office', spain: '', color: '', type: 'header' },
            { service: 'administrators_office', russian: 'Кабинет администратора', english: 'Administrator`s office', spain: '', color: '', type: 'header' },
            { service: 'registration', russian: 'Регистрация', english: 'Registration', spain: '', color: '', type: 'header' },
            { service: 'authorization', russian: 'Авторизация', english: 'Authorization', spain: '', color: '', type: 'header' },
            { service: 'password_recovery', russian: 'Восстановление пароля', english: 'Password recovery', spain: '', color: '', type: 'header' },
            { service: 'have_an_account', russian: 'Есть аккаунт? ', english: 'Have an account? ', spain: '', color: '', type: 'header' },
            { service: 'fill_account', russian: 'Заполните аккаунт и начнем', english: 'Fill in your account details and letёs get started.', spain: '', color: '', type: 'header' },

            { service: 'no_orders', russian: 'Нет заказов', english: 'No orders', spain: '', color: '', type: 'content' },
            { service: 'password', russian: 'пароль', english: 'password', spain: '', color: '', type: 'content' },
            { service: 'email', russian: 'пароль', english: 'email', spain: '', color: '', type: 'content' },
            { service: 'selected_orders', russian: 'Выбрано заказов', english: 'Selected orders', spain: '', color: '', type: 'content' },
            { service: '', russian: '', english: '', spain: '', color: '', type: 'content' },
            { service: '', russian: '', english: '', spain: '', color: '', type: 'content' },

            // { service: '', russian: '', english: '', spain: '', color: '', type: 'page_title' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'page_title' },

            { service: 'carrier', russian: 'Перевозчик', english: 'Carrier', spain: '', color: '', type: 'role' },
            { service: 'customer', russian: 'Заказчик', english: 'Customer', spain: '', color: '', type: 'role' },
            { service: 'manager', russian: 'Менеджер', english: 'Manager', spain: '', color: '', type: 'role' },
            { service: 'administrator', russian: 'Администратор', english: 'Administrator', spain: '', color: '', type: 'role' },


            { service: 'not_empty', russian: 'не может быть пустым', english: 'can`t be empty', spain: '', color: '', type: 'validation' },
            { service: 'to_short', russian: 'не может быть короче', english: 'can`t be shorter than', spain: '', color: '', type: 'validation' },
            { service: 'to_long', russian: 'не может быть длиннее', english: 'can`t be longer than', spain: '', color: '', type: 'validation' },
            { service: 'format_error', russian: 'неверного формата', english: 'has wrong format', spain: '', color: '', type: 'validation' },
            { service: 'symbols', russian: 'символов', english: 'symbols', spain: '', color: '', type: 'validation' },
            { service: 'compare_passwords', russian: 'пароли не совпадают', english: 'passwords do not match', spain: '', color: '', type: 'validation' },
            { service: 'select_role', russian: 'выберите роль', english: 'select role', spain: '', color: '', type: 'validation' },
            { service: 'confirmation_code', russian: 'код подтверждения', english: 'confirmation code', spain: '', color: '', type: 'validation' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'validation' },

            { service: 'your_email', russian: 'Ваш email', english: 'Your email', spain: '', color: '', type: 'place_holder' },
            { service: 'your_password', russian: 'Ваш пароль', english: 'Your password', spain: '', color: '', type: 'place_holder' },
            { service: 'who_are_you', russian: 'Вы заказчик или перевозчик?', english: 'Are you a customer or carrier?', spain: '', color: '', type: 'place_holder' },
            { service: 'password_repeat', russian: 'Пароль еще раз', english: 'Repeat password again', spain: '', color: '', type: 'place_holder' },
            { service: 'Сonfirmation_code', russian: 'Код подтверждения', english: 'Сonfirmation code', spain: '', color: '', type: 'place_holder' },
            // { service: '', russian: '', english: '', spain: '', color: '', type: 'place_holder' },

            { service: 'code_sent', russian: 'Код отправлен', english: 'Сode sent', spain: '', color: '', type: 'notification' },
            { service: 'password_changed', russian: 'Пароль изиенен, доступ восстановлен, вы авторизованы', english: 'Password changed, access restored, you are logged in', spain: '', color: '', type: 'notification' },
            { service: 'logged_in', russian: 'Вы авторизованы', english: 'You are logged in', spain: '', color: '', type: 'notification' },
            { service: 'registered', russian: 'Вы зарегистрированы, ссылка для активации аккаунта отрправлена на указанный email', english: 'You are registered, a link to activate your account has been sent to the specified email', spain: '', color: '', type: 'notification' },
            { service: 'new_orders_received', russian: 'Поступили новые заказы:', english: 'New orders received:', spain: '', color: '', type: 'notification' },
            { service: 'new_order_received', russian: 'Поступил новый заказ', english: 'New order received', spain: '', color: '', type: 'notification' },
            { service: 'orders_taken', russian: 'Взяты в работу заказы:', english: 'Orders taken:', spain: '', color: '', type: 'notification' },
            { service: 'order_taken', russian: 'Взят в работу заказ', english: 'Order taken', spain: '', color: '', type: 'notification' },
            { service: 'offers_accepted', russian: 'Вы приняли предложения по аукционам:', english: 'You have accepted offers for auctions:', spain: '', color: '', type: 'notification' },
            { service: 'offer_accepted', russian: 'Вы приняли предложение по аукциону', english: 'You have accepted offer for auction', spain: '', color: '', type: 'notification' },
            { service: 'offers_accepted_carrier', russian: 'Приняты ваши предложения по аукционам:', english: 'Customers accepted your offers for auctions:', spain: '', color: '', type: 'notification' },
            { service: 'offer_accepted_carrier', russian: 'Принято ваше предложение по аукциону', english: '', spain: 'Customer accepted your offer for auction', color: '', type: 'notification' },
            { service: 'start_doing', russian: 'можете приступать к выполнению', english: '', spain: 'you can start doing', color: '', type: 'notification' },
            { service: 'postponed_orders', russian: 'Отложены заказы:', english: 'Postponed orders:', spain: '', color: '', type: 'notification' },
            { service: 'postponed_order', russian: 'Отложен заказ', english: 'Postponed order:', spain: '', color: '', type: 'notification' },
            { service: 'restored_orders', russian: 'Вы восстановили заказы:', english: 'You have restored orders:', spain: '', color: '', type: 'notification' },
            { service: 'restored_orders', russian: 'Вы восстановили заказ', english: 'You have restored order', spain: '', color: '', type: 'notification' },
            { service: 'check_restored', russian: 'он находится в отложенных, можете отправить его после проверки', english: 'it is in postponed, you can send it after verification', spain: '', color: '', type: 'notification' },
            { service: 'orders_canceled', russian: 'Отменены заказы:', english: 'Canceled orders:', spain: '', color: '', type: 'notification' },
            { service: 'order_canceled', russian: 'Отменен заказ', english: 'Canceled order:', spain: '', color: '', type: 'notification' },
            { service: 'not_loading', russian: 'В связи с незагрузкой', english: 'Due to not loading', spain: '', color: '', type: 'notification' },
            { service: 'non_arrival', russian: 'В связи с не подачей', english: 'Due to non-arrival', spain: '', color: '', type: 'notification' },
            { service: 'affect_your_rating', russian: 'обратите внимание, это влияет на ваш рейтинг', english: 'please note that this will affect your rating', spain: '', color: '', type: 'notification' },
            { service: 'affect_carrier_rating', russian: 'Это повлияет на рейтинг перевозчика', english: 'This will affect the rating of the carrier', spain: '', color: '', type: 'notification' },
            { service: 'affect_customer_rating', russian: 'Это повлияет на рейтинг заказчика', english: 'This will affect the rating of the customer', spain: '', color: '', type: 'notification' },
            { service: 'restore_to_resend', russian: 'восстановите его для повторной отправки', english: 'restore it to resend the order', spain: '', color: '', type: 'notification' },
            { service: 'canceled_disrupted_orders', russian: 'Вы отменили сорванные заказы:', english: 'You canceled disrupted orders:', spain: '', color: '', type: 'notification' },
            { service: 'canceled_disrupted_order', russian: 'Вы отменили сорванный заказ', english: 'You canceled disrupted order', spain: '', color: '', type: 'notification' },
            { service: 'completed_orders', russian: 'Завершены заказы:', english: 'Completed orders:', spain: '', color: '', type: 'notification' },
            { service: 'completed_order', russian: 'Завершен заказ', english: 'Completed order:', spain: '', color: '', type: 'notification' },
            { service: 'customer_completed_orders', russian: 'Заказчик завершил заказы:', english: 'The customer completed orders:', spain: '', color: '', type: 'notification' },
            { service: 'customer_completed_order', russian: 'Заказчик завершил заказ', english: 'The customer completed order:', spain: '', color: '', type: 'notification' },
            { service: 'new_offers', russian: 'Поступили новые предложения к аукционам', english: 'New offers for auctions', spain: '', color: '', type: 'notification' },
            { service: 'changed_offers', russian: 'Измемены предложения к аукционам', english: 'Changed offers for auctions', spain: '', color: '', type: 'notification' },
            { service: 'removed_offers', russian: 'Удалены предложения к аукционам', english: 'Removed offers for auctions', spain: '', color: '', type: 'notification' },
            { service: 'new_offer', russian: 'Поступило новое предложение к аукциону', english: 'New offer for auction', spain: '', color: '', type: 'notification' },
            { service: 'changed_offer', russian: 'Измемено предложение к аукциону', english: 'Changed offer for auction', spain: '', color: '', type: 'notification' },
            { service: 'removed_offer', russian: 'Удалено предложение к аукциону', english: 'Removed offer for auction', spain: '', color: '', type: 'notification' },
            { service: 'order_notifications', russian: 'Заказ', english: 'Order', spain: '', color: '', type: 'notification' },
            { service: 'orders_notifications', russian: 'Заказы:', english: 'Orders:', spain: '', color: '', type: 'notification' },
            { service: 'auction_notifications', russian: 'Аукцион', english: 'Auction', spain: '', color: '', type: 'notification' },
            { service: 'auctions_notifications', russian: 'Аукционы:', english: 'Auctions:', spain: '', color: '', type: 'notification' },
            { service: 'converted_one', russian: 'преобразован', english: 'converted', spain: '', color: '', type: 'notification' },
            { service: 'converted_many', russian: 'преобразованы', english: 'converted', spain: '', color: '', type: 'notification' },
            { service: 'can_take_it', russian: 'вы можете взять в работу на текущих условиях', english: 'you can take it on current terms', spain: '', color: '', type: 'notification' },
            { service: 'to_order', russian: 'в заказ', english: 'to order', spain: '', color: '', type: 'notification' },
            { service: 'to_auction', russian: 'в аукцион', english: 'to auction', spain: '', color: '', type: 'notification' },
            { service: 'canceled_point', russian: 'Отменена точка', english: 'Canceled point', spain: '', color: '', type: 'notification' },
            { service: 'canceled_points', russian: 'Отменены точки:', english: 'Canceled points:', spain: '', color: '', type: 'notification' },
            { service: 'completed_point', russian: 'Завершена точка', english: 'Completed point', spain: '', color: '', type: 'notification' },
            { service: 'completed_points', russian: 'Завершены точки:', english: 'Completed points:', spain: '', color: '', type: 'notification' },
            { service: 'restored_point', russian: 'Восстановлена точка', english: 'Restored point', spain: '', color: '', type: 'notification' },
            { service: 'restored_points', russian: 'Восстановлены точки:', english: 'Restored points:', spain: '', color: '', type: 'notification' },
            { service: 'in_work_point', russian: 'Взята в работу точка', english: 'Taken into work point', spain: '', color: '', type: 'notification' },
            { service: 'in_work_points', russian: 'Взяты в работу точки', english: 'Taken into work points', spain: '', color: '', type: 'notification' },
            { service: 'on_order', russian: 'по заказу', english: '', spain: 'on order', color: '', type: 'notification' },
            { service: 'on_orders', russian: 'пл заказам', english: 'on orders:', spain: '', color: '', type: 'notification' },
        ]

        makeAutoObservable(this)
    }

    setTranslation(value) {
        this._translation = value
    }

    get translation() {
        return this._translation
    }

    setLanguage(value) {
        this._language = value
    }

    get language() {
        return this._language
    }
}




