//@ts-ignore
import { setTime } from "../../../modules/setTime";

export const initialValue = {
  order_comment: "",
  cost: undefined,
  mileage: undefined,
  carrierId: undefined,
  order_status: "",
  final_status: "",
  userId: undefined,
  country: "",
  city: "",
  type: "",
  load_capacity: "",
  side_type: "",
  thermo_bag: false,
  hydraulic_platform: false,
  side_loading: false,
  glass_stand: false,
  refrigerator_minus: false,
  refrigerator_plus: false,
  thermo_van: false,
  order_type: "",
  userInfoId: undefined,
  pointsIntegrationId: "",
  option: "new",
  files: "",
  for_partner: undefined,
  for_group: undefined,
  direction_response: JSON.stringify([]),
  for_who: undefined,
};

const initialTime = new Date();

export const pointInitialValue = [
  {
    id: 1,
    sequence: 1,
    point: {
      value: "",
      isDirty: false,
      isEmptyError: true,
      errorMessage: "",
    },
    latitude: undefined,
    longitude: undefined,
    time: {
      value: setTime(initialTime, 60, "form"),
      isDirty: false,
      isEmptyError: false,
      errorMessage: "",
    },
    status: "new",
    name: "",
    customer_comment: {
      value: "",
      isDirty: false,
      minLengthError: false,
      maxLengthError: false,
      isEmptyError: true,
      errorMessage: "",
    },
    carrier_comment: "",
    services: "",
    updated_by: undefined,
    orderIntegrationId: '',
    city: "",
  },
  {
    id: 2,
    sequence: 50,
    point: {
      value: "",
      isDirty: false,
      isEmptyError: true,
      errorMessage: "",
    },
    latitude: undefined,
    longitude: undefined,
    time: {
      value: setTime(initialTime, 90, "form"),
      isDirty: false,
      isEmptyError: false,
      errorMessage: "",
    },
    status: "new",
    name: "",
    customer_comment: {
      value: "",
      isDirty: false,
      minLengthError: false,
      maxLengthError: false,
      isEmptyError: true,
      errorMessage: "",
    },
    carrier_comment: "",
    services: "",
    updated_by: undefined,
    orderIntegrationId: '',
    city: "",
  },
];
