export interface Order {
    order_comment: string,
    cost: number | undefined,
    mileage: number | undefined,
    carrierId: number | undefined,
    order_status: string,
    final_status: string,
    userId: number | undefined,
    country: string,
    city: string,
    type: string,
    load_capacity: string,
    side_type: string,
    thermo_bag: boolean,
    hydraulic_platform: boolean,
    side_loading: boolean,
    glass_stand: boolean,
    refrigerator_minus: boolean,
    refrigerator_plus: boolean,
    thermo_van: boolean,
    order_type: string,
    userInfoId: number | undefined,
    pointsIntegrationId: string,
    option: string,
    files: string,
    for_partner: number | undefined,
    for_group: number | undefined,
    direction_response: string,
    for_who: number| undefined,
}


